#ifndef ORIGINAL_COROUTINES_H
#define ORIGINAL_COROUTINES_H
#include "optional.h"
#include "executor.h"
#include <coroutine>
#include <exception>
#include "awaitable.h"
#include "syncPoint.h"
#include "thread.h"

/**
 * @file coroutines.h
 * @brief C++20 coroutine support with generator pattern implementation
 *
 * This file implements a type-safe, lazy-evaluation generator pattern using
 * C++20 coroutines. The generator provides a convenient way to create and
 * consume sequences of values with minimal memory overhead and efficient
 * suspension/resumption semantics.
 *
 * Key Features:
 * - Lazy evaluation: Values are generated on-demand
 * - Exception safety: Proper exception propagation through coroutine boundaries
 * - Iterator support: Compatible with range-based for loops and STL algorithms
 * - Move semantics: Efficient transfer of coroutine state
 * - Resource management: Automatic cleanup of coroutine handles
 * - Type safety: Compile-time type checking for generated values
 *
 * @note The generator suspends after each yielded value, allowing consumers
 *       to control the execution flow and memory usage.
 * @note Coroutine state is automatically destroyed when the generator goes
 *       out of scope, preventing resource leaks.
 */

namespace original {
    template<typename A>
    concept Awaiter = requires(A awaiter, std::coroutine_handle<> handle) {
        { awaiter.await_ready() } -> std::same_as<bool>;
        { awaiter.await_suspend(handle) } -> std::same_as<void>;
        { awaiter.await_resume() };
    };

    template<typename A>
    concept Awaitable = Awaiter<A> || requires(A awaitable) {
        { awaitable.operator co_await() } -> Awaiter;
    };

    /**
     * @class coroutine
     * @brief Namespace for coroutine-related utilities and generator implementation
     * @details Provides a generator class template that implements the C++20 coroutine
     *          protocol for creating lazy sequences of values.
     */
    class coroutine {
    public:
        /**
         * @class generator
         * @tparam TYPE Type of values generated by the coroutine
         * @brief Lazy sequence generator using C++20 coroutines
         * @details Implements the coroutine promise protocol to create generators
         *          that can yield sequences of values. Supports range-based for loops,
         *          manual iteration, and exception propagation.
         *
         * The generator maintains the following states:
         * - Suspended: Waiting to be resumed (initial and after each yield)
         * - Running: Currently executing coroutine logic
         * - Completed: All values have been generated
         *
         * @note Generators are move-only types to prevent accidental copying of
         *       coroutine state.
         * @note Iterators become invalid when the generator is destroyed or moved.
         */
        template<typename TYPE>
        class generator {
        public:
            struct promise_type;
        private:
            using handle = std::coroutine_handle<promise_type>;  ///< Coroutine handle type

            handle handle_;  ///< Underlying coroutine handle

        public:
            /**
             * @struct promise_type
             * @brief Implements the coroutine promise interface for generator
             * @details Manages the coroutine state, value storage, and exception
             *          handling according to the C++20 coroutine specification.
             */
            struct promise_type {
                bool initial_status = false;      ///< Tracks if coroutine has started execution
                alternative<TYPE> value_;        ///< Storage for the current yielded value
                std::exception_ptr e_;           ///< Captured exceptions for propagation

                /**
                 * @brief Creates the generator object from this promise
                 * @return generator instance associated with this promise
                 */
                generator get_return_object();

                /**
                 * @brief Defines initial suspension behavior
                 * @return suspend_always to start in suspended state
                 * @note Lazy initialization: coroutine starts suspended
                 */
                static std::suspend_always initial_suspend();

                /**
                 * @brief Defines final suspension behavior
                 * @return suspend_always to keep frame alive for cleanup
                 * @note Prevents automatic destruction of coroutine frame
                 */
                static std::suspend_always final_suspend() noexcept;

                /**
                 * @brief Handles coroutine completion without value
                 */
                static void return_void();

                /**
                 * @brief Handles value yielding from coroutine
                 * @param value Value to yield to caller
                 * @return suspend_always to suspend after yielding
                 * @note Stores the value and suspends execution
                 */
                std::suspend_always yield_value(TYPE value);

                /**
                 * @brief Captures exceptions thrown from coroutine
                 */
                void unhandled_exception();

                /**
                 * @brief Re-throws any captured exception
                 * @throws The exception previously captured by unhandled_exception
                 */
                void rethrow_if_exception() const;
            };

            /**
             * @class iterator
             * @brief Input iterator for generator range-based operations
             * @details Provides input iterator interface for using generator
             *          with range-based for loops and STL algorithms.
             *
             * Iterator invalidation:
             * - Invalidated when generator is destroyed
             * - Invalidated when generator is moved from
             * - Safe for single-pass algorithms only
             */
            class iterator {
                generator* gen_;  ///< Pointer to parent generator
                bool end_;        ///< Flag indicating end iterator

                /**
                 * @brief Default constructor creates end iterator
                 */
                iterator();

                /**
                 * @brief Constructs iterator for specific generator
                 * @param gen Pointer to generator to iterate over
                 */
                explicit iterator(generator* gen);
            public:
                friend coroutine;

                /**
                 * @brief Advances iterator to next value
                 * @return Reference to this iterator
                 * @note Calls generator::next() internally
                 */
                iterator& operator++();

                /**
                 * @brief Dereferences iterator to get current value
                 * @return Current value from generator
                 * @throws nullPointerError if dereferencing end iterator
                 */
                TYPE operator*();

                /**
                 * @brief Checks iterator inequality
                 * @param other Iterator to compare with
                 * @return true if iterators are not equal
                 */
                bool operator!=(const iterator& other) const;

                /**
                 * @brief Checks iterator equality
                 * @param other Iterator to compare with
                 * @return true if iterators are equal
                 */
                bool operator==(const iterator& other) const;
            };

            generator(const generator&) = delete;            ///< Copy constructor deleted
            generator& operator=(const generator&) = delete; ///< Copy assignment deleted

            /**
             * @brief Move constructor transfers coroutine ownership
             * @param other Generator to move from
             * @note Source generator becomes empty after move
             */
            generator(generator&& other) noexcept;

            /**
             * @brief Move assignment operator transfers coroutine ownership
             * @param other Generator to move from
             * @return Reference to this generator
             * @note Destroys current coroutine handle before transfer
             */
            generator& operator=(generator&& other) noexcept;

            generator() = default;  ///< Default constructor creates empty generator

            /**
             * @brief Constructs generator from coroutine handle
             * @param h Coroutine handle to manage
             */
            explicit generator(handle h);

            /**
             * @brief Gets begin iterator for range-based operations
             * @return Iterator positioned at first value
             * @note Resumes coroutine to get first value
             */
            iterator begin();

            /**
             * @brief Gets end iterator for range-based operations
             * @return End iterator marker
             */
            static iterator end();

            /**
             * @brief Checks if coroutine has been launched
             * @return true if coroutine has started execution
             */
            [[nodiscard]] bool launched() const;

            /**
             * @brief Checks if generator has more values
             * @return true if next() would return a value
             */
            [[nodiscard]] bool hasNext() const;

            /**
             * @brief Peeks at current value without advancing
             * @return optional containing current value if available
             * @note Does not resume coroutine or change state
             */
            [[nodiscard]] alternative<TYPE> peek() const;

            /**
             * @brief Advances generator and gets next value
             * @return optional containing next value if available
             * @note Resumes coroutine execution and may throw exceptions
             */
            alternative<TYPE> next();

            /**
             * @brief Destructor cleans up coroutine resources
             * @note Automatically destroys coroutine handle
             */
            ~generator();
        };

        template<typename TYPE>
        class task;

        template <typename T>
        struct flattenTask { using type = T; };

        template <typename T>
        struct flattenTask<task<T>> { using type = T; };

        template <typename>
        struct isTaskLike : std::false_type {};

        template <typename T>
        struct isTaskLike<task<T>> : std::true_type {};

        template<typename TYPE>
        using flattenTaskType = flattenTask<TYPE>::type;

        template<typename TYPE>
        using isTask = isTaskLike<TYPE>::value;

        template<typename>
        struct isTaskArgs : std::false_type {};

        template<typename T>
        struct taskArgsType {
            using type = flattenTaskType<T>::type;
        };

        template <typename Func, typename ArgsTuple>
        struct taskInvokeResult;

        template <typename Func, typename... Args>
        struct taskInvokeResult<Func, tuple<Args...>> {
            using type = std::invoke_result_t<Func, Args...>;
        };

        template <typename Func, typename ArgsTuple>
        using taskInvokeResultType = taskInvokeResult<Func, ArgsTuple>::type;

        template<typename Pred, typename Then, typename Else>
        class taskCondition {
            Pred pred_;
            Then then_;
            Else else_;

        public:
            friend coroutine;
            explicit taskCondition(Pred p, Then t, Else e);
        };

        template<typename... Args>
        class taskArgs {
            using TupleType = tuple<std::decay_t<Args>...>;
            TupleType args_;
            executor* executor_{};

        public:
            template <typename TYPE, bool Prev>
            class bridge {
                taskArgs taskArgs_;
                task<TYPE> task_;

                bridge(taskArgs args, task<TYPE> task);
            public:
                friend coroutine;

                bridge(const bridge&) = delete;
                bridge& operator=(const bridge&) = delete;

                bridge(bridge&&) noexcept = default;
                bridge& operator=(bridge&&) noexcept = default;

                template<typename... Others>
                taskArgs<Others...>::template bridge<TYPE, Prev> operator|(taskArgs<Others...>&& args);

                template<typename... Others>
                taskArgs<Args..., Others...>::template bridge<TYPE, Prev> operator>>(taskArgs<Others...>&& args);

                template<typename Callback>
                auto operator|(Callback&& c);

                template<typename Callback>
                auto operator>>(Callback&& c);
            };

            friend coroutine;
            explicit taskArgs(TupleType args);

            taskArgs(executor* exe, TupleType args);

            taskArgs(const taskArgs&) = delete;
            taskArgs& operator=(const taskArgs&) = delete;

            taskArgs(taskArgs&& other) noexcept;
            taskArgs& operator=(taskArgs&& other) noexcept;

            taskArgs operator|(executor& executor);

            taskArgs operator>>(executor& executor);

            template<typename... Others>
            taskArgs<Others...> operator|(taskArgs<Others...>&& other);

            template<typename... Others>
            taskArgs<Args..., Others...> operator>>(taskArgs<Others...>&& other);

            template<typename Callback>
            auto operator|(Callback&& c) -> task<std::invoke_result_t<Callback>>;

            template<typename Callback>
            auto operator>>(Callback&& c) -> task<std::invoke_result_t<Callback, Args...>>;

            template<typename... Callback>
            auto operator|(tuple<Callback...>&& cs);

            template<typename... Callback>
            auto operator>>(tuple<Callback...>&& cs);

            TupleType unbind();
        };

        template<typename... Args>
        struct isTaskArgs<taskArgs<Args...>> : std::true_type {};

        template<typename... Args>
        struct taskArgsType<taskArgs<Args...>> {
            using type = tuple<Args...>;
        };

        template<typename TYPE>
        class task {
        public:
            friend coroutine;
            struct promise_type;
        private:
            enum class state {
                STANDBY,
                RUNNING,
                FINISHED,
            };

            using handle = std::coroutine_handle<promise_type>;

            handle handle_;
        public:
            struct awaitable {
                handle handle_;

                explicit awaitable(handle h);

                [[nodiscard]] bool await_ready() const noexcept;

                void await_suspend(std::coroutine_handle<> waiter) noexcept;

                TYPE await_resume() const;
            };

            struct finalAwaitable {
                bool await_ready() noexcept;

                void await_suspend(handle handle) noexcept;

                void await_resume() noexcept;
            };

            struct promise_type {
                std::coroutine_handle<> continuation_{};
                executor* executor_ = nullptr;
                syncPoint* spt_ = nullptr;
                alternative<TYPE> value_;
                std::exception_ptr e_;
                state state_ = state::STANDBY;

                task get_return_object();

                auto initial_suspend();

                finalAwaitable final_suspend() noexcept;

                void return_value(TYPE value);

                void unhandled_exception();

                void rethrow_if_exception() const;
            };

            task(const task&) = delete;
            task& operator=(const task&) = delete;

            task() = default;

            explicit task(handle h);

            void sync(syncPoint& spt);

            bool start() noexcept;

            [[nodiscard]] bool hasExecutor() const noexcept;

            task& via(executor& executor) noexcept;

            task(task&& other) noexcept;

            task& operator=(task&& other) noexcept;

            [[nodiscard]] bool started() const noexcept;

            [[nodiscard]] bool finished() const noexcept;

            [[nodiscard]] bool empty() const noexcept;

            [[nodiscard]] explicit operator bool() const noexcept;

            awaitable operator co_await() noexcept;

            template<typename U>
            task<U> operator|(task<U> rhs);

            template<typename U>
            task<U> operator>>(task<U> rhs);

            template<typename Callback>
            auto operator|(Callback&& c);

            template<typename Callback>
            auto operator>>(Callback&& c) -> task<std::invoke_result_t<Callback, TYPE>>;

            task operator|(executor& exec);

            task operator>>(executor& exec);

            task operator|(Awaiter auto&& awaiter);

            task operator>>(Awaiter auto&& awaiter);

            template<typename E, typename Handle>
            task operator|(errorCatchAwaitable<E, Handle>&& catcher);

            template<typename E, typename Handle>
            task operator>>(errorCatchAwaitable<E, Handle>&& catcher);

            template<typename Pred, typename Then, typename Else>
            auto operator|(taskCondition<Pred, Then, Else>&& condition);

            template<typename Pred, typename Then, typename Else>
            auto operator>>(taskCondition<Pred, Then, Else>&& condition);

            template<typename... Args>
            auto operator|(taskArgs<Args...>&& args);

            template<typename... Args>
            auto operator>>(taskArgs<Args...>&& args);

            template<typename... Callback>
            auto operator|(tuple<Callback...>&& cs);

            template<typename... Callback>
            auto operator>>(tuple<Callback...>&& cs);

            TYPE result();

            ~task();
        };

        template<typename Callback, typename... Args>
        static auto makeTask(Callback&& c, Args&&... args) -> task<std::invoke_result_t<Callback, Args...>>;

        template<typename Callback, typename... Args>
        static auto makeTask(executor& executor, Callback&& c, Args&&... args) -> task<std::invoke_result_t<Callback, Args...>>;

        template<typename Callback, typename... Args>
        static auto makeTask(Callback&& c, tuple<Args...> args) -> task<std::invoke_result_t<Callback, Args...>>;

        template<typename Callback, typename... Args>
        static auto makeTask(executor& executor, Callback&& c, tuple<Args...> args) -> task<std::invoke_result_t<Callback, Args...>>;

        template<typename TYPE>
        static TYPE spinRun(task<TYPE> t);

        template<typename TYPE>
        static TYPE run(task<TYPE> t);

        static bool run(const task<void>& t);

        template<typename... Args>
        static tuple<someType<std::is_void_v<Args>, bool, Args>...> whenAll(task<Args>... ts);

        template<typename... Args>
        static tuple<someType<std::is_void_v<Args>, bool, Args>...> spinWhenAll(task<Args>... ts);
    };

    template<>
    class coroutine::task<void> {
    public:
        friend coroutine;
        struct promise_type;
    private:
        enum class state {
            STANDBY,
            RUNNING,
            FINISHED,
        };

        using handle = std::coroutine_handle<promise_type>;

        handle handle_;
    public:
        struct awaitable {
            handle handle_;

            explicit awaitable(handle h);

            [[nodiscard]] bool await_ready() const noexcept;

            void await_suspend(std::coroutine_handle<> waiter) noexcept;

            void await_resume() const;
        };

        struct finalAwaitable {
            bool await_ready() noexcept;

            void await_suspend(handle handle) noexcept;

            void await_resume() noexcept;
        };

        struct promise_type {
            std::coroutine_handle<> continuation_;
            executor* executor_ = nullptr;
            syncPoint* spt_ = nullptr;
            std::exception_ptr e_;
            state state_ = state::STANDBY;

            task get_return_object();

            auto initial_suspend();

            finalAwaitable final_suspend() noexcept;

            void return_void();

            void unhandled_exception();

            void rethrow_if_exception() const;
        };

        task(const task&) = delete;
        task& operator=(const task&) = delete;

        task() = default;

        explicit task(handle h);

        void sync(syncPoint& spt) const;

        [[nodiscard]] bool start() const noexcept;

        [[nodiscard]] bool hasExecutor() const noexcept;

        task& via(executor& executor) noexcept;

        task(task&& other) noexcept;

        task& operator=(task&& other) noexcept;

        [[nodiscard]] bool started() const noexcept;

        [[nodiscard]] bool finished() const noexcept;

        [[nodiscard]] bool empty() const noexcept;

        [[nodiscard]] explicit operator bool() const noexcept;

        awaitable operator co_await() const noexcept;

        void result() const;

        template<typename U>
        task<U> operator|(task<U> rhs);

        template<typename U>
        task<U> operator>>(task<U> rhs);

        template<typename Callback>
        auto operator|(Callback&& c);

        template<typename Callback>
        auto operator>>(Callback&& c);

        task operator|(executor& exec);

        task operator>>(executor& exec);

        task operator|(Awaiter auto&& awaiter);

        task operator>>(Awaiter auto&& awaiter);

        template<typename E, typename Handle>
        task operator|(errorCatchAwaitable<E, Handle>&& catcher);

        template<typename E, typename Handle>
        task operator>>(errorCatchAwaitable<E, Handle>&& catcher);

        template<typename Pred, typename Then, typename Else>
        auto operator|(taskCondition<Pred, Then, Else>&& condition);

        template<typename Pred, typename Then, typename Else>
        auto operator>>(taskCondition<Pred, Then, Else>&& condition);

        template<typename... Callback>
        auto operator|(tuple<Callback...>&& cs);

        template<typename... Callback>
        auto operator>>(tuple<Callback...>&& cs);

        ~task();
    };

    template <>
    struct coroutine::flattenTask<void> { using type = bool; };

    template <>
    struct coroutine::flattenTask<coroutine::task<void>> { using type = bool; };

    template<typename Callback>
    auto operator|(executor& exec, Callback&& c);

    template<typename Callback>
    auto operator>>(executor& exec, Callback&& c);

    template<typename... Callback>
    auto operator|(executor& exec, tuple<Callback...>&& cs);

    template<typename... Callback>
    auto operator>>(executor& exec, tuple<Callback...>&& cs);

    template<typename... Args>
    coroutine::taskArgs<Args...> coBind(Args&&... args);

    template<typename... Args>
    coroutine::taskArgs<Args...> operator|(executor& executor, coroutine::taskArgs<Args...>&& args);

    template<typename... Args>
    coroutine::taskArgs<Args...> operator>>(executor& executor, coroutine::taskArgs<Args...>&& args);

    template<typename... Callback>
    tuple<std::decay_t<Callback>...> coParallel(Callback&&... c);

    template<typename Pred, typename Then, typename Else>
    auto coIfElse(Pred&& p, Then&& t, Else&& e);
}

template <typename TYPE>
original::coroutine::generator<TYPE>
original::coroutine::generator<TYPE>::promise_type::get_return_object()
{
    return generator{handle::from_promise(*this)};
}

template <typename TYPE>
std::suspend_always original::coroutine::generator<TYPE>::promise_type::initial_suspend()
{
    return std::suspend_always{};
}

template <typename TYPE>
std::suspend_always original::coroutine::generator<TYPE>::promise_type::final_suspend() noexcept
{
    return std::suspend_always{};
}

template <typename TYPE>
void original::coroutine::generator<TYPE>::promise_type::return_void() {}

template <typename TYPE>
std::suspend_always original::coroutine::generator<TYPE>::promise_type::yield_value(TYPE value)
{
    if (!this->initial_status) {
        this->initial_status = true;
    }
    this->value_ = std::move(value);
    return std::suspend_always{};
}

template <typename TYPE>
void original::coroutine::generator<TYPE>::promise_type::unhandled_exception()
{
    this->e_ = std::current_exception();
}

template <typename TYPE>
void original::coroutine::generator<TYPE>::promise_type::rethrow_if_exception() const
{
    if (this->e_)
        std::rethrow_exception(this->e_);
}

template <typename TYPE>
original::coroutine::generator<TYPE>::iterator::iterator() : gen_(nullptr), end_(true) {}

template <typename TYPE>
original::coroutine::generator<TYPE>::iterator::iterator(generator* gen) : gen_(gen), end_(false)
{
    if (!this->gen_) {
        this->end_ = true;
        return;
    }
    ++*this;
}

template <typename TYPE>
original::coroutine::generator<TYPE>::iterator&
original::coroutine::generator<TYPE>::iterator::operator++()
{
    if (this->end_)
        return *this;
    if (auto gen_next = this->gen_->next(); !gen_next) {
        this->end_ = true;
    }
    return *this;
}

template <typename TYPE>
TYPE original::coroutine::generator<TYPE>::iterator::operator*()
{
    if (this->end_)
        throw nullPointerError("Dereferencing end iterator");
    return *this->gen_->peek();
}

template <typename TYPE>
bool original::coroutine::generator<TYPE>::iterator::operator!=(const iterator& other) const
{
    return !(*this == other);
}

template <typename TYPE>
bool original::coroutine::generator<TYPE>::iterator::operator==(const iterator& other) const
{
    if (this->end_ && other.end_)
        return true;
    if (this->end_ != other.end_)
        return false;
    return this->gen_ == other.gen_;
}

template <typename TYPE>
original::coroutine::generator<TYPE>::generator(generator&& other) noexcept
{
    this->handle_ = other.handle_;
    other.handle_ = nullptr;
}

template <typename TYPE>
original::coroutine::generator<TYPE>&
original::coroutine::generator<TYPE>::operator=(generator&& other) noexcept
{
    if (this == &other) {
        return *this;
    }

    if (this->handle_) {
        this->handle_.destroy();
    }

    this->handle_ = other.handle_;
    other.handle_ = nullptr;
    return *this;
}

template <typename TYPE>
original::coroutine::generator<TYPE>::generator(handle h) : handle_(std::move(h)) {}

template <typename TYPE>
original::coroutine::generator<TYPE>::iterator
original::coroutine::generator<TYPE>::begin()
{
    return iterator{this};
}

template <typename TYPE>
original::coroutine::generator<TYPE>::iterator
original::coroutine::generator<TYPE>::end()
{
    return iterator{};
}

template <typename TYPE>
bool original::coroutine::generator<TYPE>::launched() const
{
    return this->handle_.promise().initial_status;
}

template <typename TYPE>
bool original::coroutine::generator<TYPE>::hasNext() const
{
    return this->handle_ && !this->handle_.done();
}

template <typename TYPE>
original::alternative<TYPE> original::coroutine::generator<TYPE>::peek() const
{
    return this->handle_.promise().value_;
}

template <typename TYPE>
original::alternative<TYPE>
original::coroutine::generator<TYPE>::next()
{
    if (!this->hasNext())
        return alternative<TYPE>{};

    this->handle_.resume();
    this->handle_.promise().rethrow_if_exception();

    if (!this->hasNext())
        return alternative<TYPE>{};

    return this->handle_.promise().value_;
}

template <typename TYPE>
original::coroutine::generator<TYPE>::~generator()
{
    if (this->handle_)
        this->handle_.destroy();
}

template <typename Pred, typename Then, typename Else>
original::coroutine::taskCondition<Pred, Then, Else>::taskCondition(Pred p, Then t, Else e)
    : pred_(std::move(p)), then_(std::move(t)), else_(std::move(e)) {}

template <typename ... Args>
template <typename TYPE, bool Prev>
original::coroutine::taskArgs<Args...>::bridge<TYPE, Prev>::bridge(taskArgs args, task<TYPE> task)
    : taskArgs_(std::move(args)), task_(std::move(task)) {}

template <typename ... Args>
template <typename TYPE, bool Prev>
template <typename ... Others>
original::coroutine::taskArgs<Others...>::template bridge<TYPE, Prev>
original::coroutine::taskArgs<Args...>::bridge<TYPE, Prev>::operator|(taskArgs<Others...>&& args)
{
    auto new_args = std::move(this->taskArgs_) |  std::move(args);
    using bridgeType = taskArgs<Others...>::template bridge<TYPE, Prev>;
    return bridgeType{std::move(new_args), std::move(this->task_)};
}

template <typename ... Args>
template <typename TYPE, bool Prev>
template <typename ... Others>
original::coroutine::taskArgs<Args..., Others...>::template bridge<TYPE, Prev>
original::coroutine::taskArgs<Args...>::bridge<TYPE, Prev>::operator>>(taskArgs<Others...>&& args)
{
    auto new_args = std::move(this->taskArgs_) >> std::move(args);
    using bridgeType = taskArgs<Args..., Others...>::template bridge<TYPE, Prev>;
    return bridgeType(std::move(new_args), std::move(this->task_));
}

template <typename ... Args>
template <typename TYPE, bool Prev>
template <typename Callback>
auto original::coroutine::taskArgs<Args...>::bridge<TYPE, Prev>::operator|(Callback&& c)
{
    if (this->task_.empty())
        throw valueError("Can not combine empty tasks");

    auto exec = this->taskArgs_.executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");
    this->task_.via(*exec);

    auto bridge = []<typename Func>(executor* exe, task<TYPE> t, Func f) mutable -> task<std::invoke_result_t<Func>> {
        auto new_task = std::move(t) | std::forward<Func>(f);
        new_task.via(*exe);
        co_return co_await new_task;
    };

    using Func = std::decay_t<Callback>;
    Func func_copy{std::forward<Callback>(c)};
    auto task = bridge(exec, std::move(this->task_), std::move(func_copy));
    task.via(*exec);
    return task;
}

template <typename ... Args>
template <typename TYPE, bool Prev>
template <typename Callback>
auto original::coroutine::taskArgs<Args...>::bridge<TYPE, Prev>::operator>>(Callback&& c)
{
    if (this->task_.empty())
        throw valueError("Can not combine empty tasks");

    auto exec = this->taskArgs_.executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");
    this->task_.via(*exec);

    using Func = std::decay_t<Callback>;
    Func func_copy{std::forward<Callback>(c)};
    if constexpr (!Prev) {
        auto bridge = []<typename Func, typename... Params>(executor* exe, task<TYPE> t, Func f, taskArgs<Params...> args)
            -> task<std::invoke_result_t<Func, Params...>> {
            co_await t;
            co_return co_await makeTask(*exe, std::move(f), std::move(args.unbind()));
        };
        auto task = bridge(exec, std::move(this->task_), std::move(func_copy), std::move(this->taskArgs_));
        task.via(*exec);
        return task;
    } else {
        auto bridge = []<typename Func, typename... Params>(executor* exe, task<TYPE> t, Func f, taskArgs<Params...> args)
            -> task<std::invoke_result_t<Func, TYPE, Params...>> {
            TYPE tmp = co_await t;
            auto new_args = tuple{std::move(tmp)} + std::move(args.unbind());
            co_return co_await makeTask(*exe, std::move(f), std::move(new_args));
        };
        auto task = bridge(exec, std::move(this->task_), std::move(func_copy), std::move(this->taskArgs_));
        task.via(*exec);
        return task;
    }
}

template <typename ... Args>
original::coroutine::taskArgs<Args...>::taskArgs(TupleType args)
    : args_(std::move(args)) {}

template <typename ... Args>
original::coroutine::taskArgs<Args...>::taskArgs(executor* exe, TupleType args)
    : taskArgs(std::move(args)) {
    this->executor_ = exe;
}

template <typename ... Args>
original::coroutine::taskArgs<Args...>::taskArgs(taskArgs&& other) noexcept
{
    this->args_ = std::move(other.args_);
    this->executor_ = other.executor_;
    other.executor_ = nullptr;
}

template <typename ... Args>
original::coroutine::taskArgs<Args...>&
original::coroutine::taskArgs<Args...>::operator=(taskArgs&& other) noexcept
{
    if (this == &other)
        return *this;

    this->args_ = std::move(other.args_);
    this->executor_ = other.executor_;
    other.executor_ = nullptr;
    return *this;
}

template <typename ... Args>
original::coroutine::taskArgs<Args...>
original::coroutine::taskArgs<Args...>::operator|(executor& executor)
{
    this->executor_ = &executor;
    return std::move(*this);
}

template <typename ... Args>
original::coroutine::taskArgs<Args...>
original::coroutine::taskArgs<Args...>::operator>>(executor& executor)
{
    return *this | executor;
}

template <typename... Args>
template <typename... Others>
original::coroutine::taskArgs<Others...>
original::coroutine::taskArgs<Args...>::operator|(taskArgs<Others...>&& other)
{
    if (!other.executor_)
        return other | *this->executor_;
    return other;
}

template <typename... Args>
template <typename... Others>
original::coroutine::taskArgs<Args..., Others...>
original::coroutine::taskArgs<Args...>::operator>>(taskArgs<Others...>&& other)
{
    auto new_args = std::move(this->args_) + std::move(other.args_);
    executor* new_executor = this->executor_ ? this->executor_ : other.executor_;
    return taskArgs<Args..., Others...>{new_executor, std::move(new_args)};
}

template <typename ... Args>
template <typename Callback>
auto original::coroutine::taskArgs<Args...>::operator|(Callback&& c) -> task<std::invoke_result_t<Callback>>
{
    if (!this->executor_)
        throw sysError("Tasks without a specified executor cannot be combined");

    auto sequence = []<typename Func>(Func func, executor* exec) -> task<std::invoke_result_t<Func>> {
        co_return co_await makeTask(*exec, std::move(func));
    };

    using Func  = std::decay_t<Callback>;
    Func func_copy{std::forward<Callback>(c)};
    auto task = sequence(std::move(func_copy), this->executor_);
    task.via(*this->executor_);
    return task;
}

template <typename ... Args>
template <typename Callback>
auto original::coroutine::taskArgs<Args...>::operator>>(Callback&& c) -> task<std::invoke_result_t<Callback, Args...>>
{
    if (!this->executor_)
        throw sysError("Tasks without a specified executor cannot be combined");

    auto pipeline = []<typename Func, typename... Params>(Func func, executor* exec, tuple<Params...> params)
        -> task<std::invoke_result_t<Func, Params...>> {
        co_return co_await makeTask(*exec, std::move(func), std::move(params));
    };

    using Func  = std::decay_t<Callback>;
    Func func_copy{std::forward<Callback>(c)};
    auto task = pipeline(std::move(func_copy), this->executor_, std::move(this->args_));
    task.via(*this->executor_);
    return task;
}

template <typename ... Args>
template <typename ... Callback>
auto original::coroutine::taskArgs<Args...>::operator|(tuple<Callback...>&& cs)
{
    if (!this->executor_)
        throw sysError("Tasks without a specified executor cannot be combined");

    using TasksTuple = tuple<task<std::invoke_result_t<Callback>>...>;
    using ResultArgs = taskArgs<
        someType<
            std::is_void_v<std::invoke_result_t<Callback>>,
            bool,
            std::invoke_result_t<Callback>
        >
    ...>;

    auto sequence = []<typename... F>(tuple<F...> funcs, executor* exe) mutable
        -> task<ResultArgs> {
            auto make_tasks = []<u_integer... I, typename... Func>(indexSequence<I...>, tuple<Func...>& fn, executor* e) {
                return tuple{
                    std::move(makeTask(*e, fn.template get<I>()))...
                };
            };
            auto tasks = make_tasks(makeSequence<sizeof...(F)>(), funcs, exe);
            auto get_results = [exe]<u_integer... I>(indexSequence<I...>, TasksTuple tp) -> task<ResultArgs> {
                auto convert_to_bool = []<typename T>(task<T>& cur) -> task<someType<std::is_void_v<T>, bool, T>> {
                    if constexpr (std::is_void_v<T>) {
                        co_await cur;
                        co_return true;
                    } else {
                        co_return co_await cur;
                    }
                };
                co_return *exe >> coBind(co_await convert_to_bool(tp.template get<I>()).via(*exe)...);
            };
            auto results_tasks = get_results(makeSequence<sizeof...(F)>(), std::move(tasks));
            results_tasks.via(*exe);
            co_return co_await results_tasks;
        };

    auto exec = this->executor_;
    auto task = sequence(std::move(cs), exec);
    task.via(*exec);
    return task;
}

template <typename ... Args>
template <typename ... Callback>
auto original::coroutine::taskArgs<Args...>::operator>>(tuple<Callback...>&& cs)
{
    if (!this->executor_)
        throw sysError("Tasks without a specified executor cannot be combined");

    using TasksTuple = tuple<task<std::invoke_result_t<Callback, Args...>>...>;
    using ResultArgs = taskArgs<
        someType<
            std::is_void_v<std::invoke_result_t<Callback, Args...>>,
            bool,
            std::invoke_result_t<Callback, Args...>
        >
    ...>;

    auto sequence = []<typename... P, typename... F>(taskArgs<P...> params, tuple<F...> funcs, executor* exe) mutable
        -> task<ResultArgs> {
            auto make_tasks = []<u_integer... I, typename... Func>(indexSequence<I...>, tuple<Func...>& fn, tuple<P...> ps, executor* e) {
                return tuple{std::move(makeTask(*e, fn.template get<I>(), ps))...};
            };
            auto tasks = make_tasks(makeSequence<sizeof...(F)>(), funcs, std::move(params.unbind()), exe);
            auto get_results = [exe]<u_integer... I>(indexSequence<I...>, TasksTuple tp) -> task<ResultArgs> {
                auto convert_to_bool = []<typename T>(task<T>& cur) -> task<someType<std::is_void_v<T>, bool, T>> {
                    if constexpr (std::is_void_v<T>) {
                        co_await cur;
                        co_return true;
                    } else {
                        co_return co_await cur;
                    }
                };
                co_return *exe >> coBind(co_await convert_to_bool(tp.template get<I>()).via(*exe)...);
            };
            auto results_tasks = get_results(makeSequence<sizeof...(F)>(), std::move(tasks));
            results_tasks.via(*exe);
            co_return co_await results_tasks;
        };

    auto exec = this->executor_;
    auto task = sequence(std::move(*this), std::move(cs), exec);
    task.via(*exec);
    return task;
}

template <typename ... Args>
original::coroutine::taskArgs<Args...>::TupleType
original::coroutine::taskArgs<Args...>::unbind()
{
    this->executor_ = nullptr;
    return std::move(this->args_);
}

template <typename TYPE>
original::coroutine::task<TYPE>::awaitable::awaitable(handle h) : handle_(h) {}

template <typename TYPE>
bool original::coroutine::task<TYPE>::awaitable::await_ready() const noexcept
{
    return !this->handle_ || this->handle_.done();
}

template <typename TYPE>
void original::coroutine::task<TYPE>::awaitable::await_suspend(std::coroutine_handle<> waiter) noexcept
{
    auto& promise = this->handle_.promise();
    promise.continuation_ = waiter;

    switch (promise.state_) {
        case state::STANDBY:
        default:
            promise.state_ = state::RUNNING;
        case state::RUNNING:
            if (promise.executor_)
                promise.executor_->schedule(this->handle_);
            break;
        case state::FINISHED:
            break;
    }
}

template <typename TYPE>
TYPE original::coroutine::task<TYPE>::awaitable::await_resume() const
{
    auto& promise = this->handle_.promise();
    promise.rethrow_if_exception();
    return std::move(*promise.value_);
}

template<typename TYPE>
bool original::coroutine::task<TYPE>::finalAwaitable::await_ready() noexcept // NOLINT
{
    return false;
}

template<typename TYPE>
void original::coroutine::task<TYPE>::finalAwaitable::await_suspend(
     std::coroutine_handle<promise_type> handle) noexcept
{
    auto& promise = handle.promise();
    promise.state_ = state::FINISHED;

    if (promise.continuation_ && promise.executor_) {
        promise.executor_->schedule(promise.continuation_);
    }

    if (const auto spt = promise.spt_) {
        spt->arrive();
    }
}

template<typename TYPE>
void original::coroutine::task<TYPE>::finalAwaitable::await_resume() noexcept {} // NOLINT

template <typename TYPE>
original::coroutine::task<TYPE>
original::coroutine::task<TYPE>::promise_type::get_return_object()
{
    return task{handle::from_promise(*this)};
}

template <typename TYPE>
auto original::coroutine::task<TYPE>::promise_type::initial_suspend() // NOLINT
{
    return std::suspend_always{};
}

template <typename TYPE>
original::coroutine::task<TYPE>::finalAwaitable
original::coroutine::task<TYPE>::promise_type::final_suspend() noexcept
{
    return finalAwaitable{};
}

template <typename TYPE>
void original::coroutine::task<TYPE>::promise_type::return_value(TYPE value)
{
    this->value_ = std::move(value);
}

template <typename TYPE>
void original::coroutine::task<TYPE>::promise_type::unhandled_exception()
{
    this->e_ = std::current_exception();
}

template <typename TYPE>
void original::coroutine::task<TYPE>::promise_type::rethrow_if_exception() const
{
    if (this->e_)
        std::rethrow_exception(this->e_);
}

template <typename TYPE>
original::coroutine::task<TYPE>::task(handle h) : handle_(h) {}

template <typename TYPE>
void original::coroutine::task<TYPE>::sync(syncPoint& spt)
{
    if (this->empty())
        throw sysError("Can not sync with an empty task");
    if (this->started())
        throw sysError("Can not sync with a started task");
    this->handle_.promise().spt_ = &spt;
}

template<typename TYPE>
bool original::coroutine::task<TYPE>::start() noexcept {
    if (this->empty())
        return false;

    switch (auto& promise = this->handle_.promise(); promise.state_) {
        case state::STANDBY:
            if (this->hasExecutor()){
                promise.state_ = state::RUNNING;
                promise.executor_->schedule(this->handle_);
                return true;
            }
            break;
        case state::RUNNING:
        case state::FINISHED:
        default:
            break;
    }
    return false;
}

template <typename TYPE>
bool original::coroutine::task<TYPE>::hasExecutor() const noexcept
{
    if (this->empty())
        return false;

    return this->handle_.promise().executor_;
}

template<typename TYPE>
original::coroutine::task<TYPE>&
original::coroutine::task<TYPE>::via(executor& executor) noexcept {
    if (this->empty())
        return *this;

    auto& promise = this->handle_.promise();
    promise.executor_ = &executor;
    return *this;
}

template <typename TYPE>
original::coroutine::task<TYPE>::task(task&& other) noexcept
{
    this->handle_ = other.handle_;
    other.handle_ = nullptr;
}

template <typename TYPE>
original::coroutine::task<TYPE>&
original::coroutine::task<TYPE>::operator=(task&& other) noexcept
{
    if (this == &other)
        return *this;

    if (!this->empty())
        this->handle_.destroy();

    this->handle_ = other.handle_;
    other.handle_ = nullptr;
    return *this;
}

template<typename TYPE>
bool original::coroutine::task<TYPE>::started() const noexcept {
    if (this->empty())
        return false;

    auto& promise = this->handle_.promise();
    return promise.state_ != state::STANDBY;
}

template <typename TYPE>
bool original::coroutine::task<TYPE>::finished() const noexcept
{
    if (this->empty())
        return false;

    auto& promise = this->handle_.promise();
    return promise.state_ == state::FINISHED && this->handle_.done();
}

template<typename TYPE>
bool original::coroutine::task<TYPE>::empty() const noexcept {
    return !this->handle_;
}

template <typename TYPE>
original::coroutine::task<TYPE>::operator bool() const noexcept
{
    return this->handle_ != nullptr;
}

template <typename TYPE>
original::coroutine::task<TYPE>::awaitable
original::coroutine::task<TYPE>::operator co_await() noexcept
{
    return awaitable{this->handle_};
}

template <typename TYPE>
template <typename U>
original::coroutine::task<U>
original::coroutine::task<TYPE>::operator|(task<U> rhs)
{
    if (this->empty() || rhs.empty())
        throw valueError("Can not combine empty tasks");

    auto sequence = []<typename LHS, typename RHS>(task<LHS> l, task<RHS> r) mutable -> task<RHS> {
        co_await l;
        co_return co_await r;
    };
    const auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");
    auto task = sequence(std::move(*this), std::move(rhs));
    task.via(*exec);
    return task;
}

template <typename TYPE>
template <typename U>
original::coroutine::task<U>
original::coroutine::task<TYPE>::operator>>(task<U> rhs)
{
    if (this->empty() || rhs.empty())
        throw valueError("Can not combine empty tasks");

    auto pipeline = []<typename LHS, typename RHS>(task<LHS> l, task<RHS> r) mutable -> task<RHS> {
        LHS tmp = co_await l;
        co_return co_await r(std::move(tmp));
    };
    const auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");
    auto task = pipeline(std::move(*this), std::move(rhs));
    task.via(*exec);
    return task;
}

template <typename TYPE>
template <typename Callback>
auto original::coroutine::task<TYPE>::operator|(Callback&& c)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    return std::move(*this) | std::move(makeTask(*exec, std::forward<Callback>(c)));
}

template <typename TYPE>
template <typename Callback>
auto original::coroutine::task<TYPE>::operator>>(Callback&& c) -> task<std::invoke_result_t<Callback, TYPE>>
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    auto pipeline = []<typename LHS, typename RHS>(executor& exec, task<LHS> l, RHS r) mutable
        -> task<std::invoke_result_t<RHS, LHS>> {
        LHS tmp = co_await l;
        auto rhs = makeTask(exec, std::forward<RHS>(r), std::move(tmp));
        co_return co_await rhs;
    };
    auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    using Func  = std::decay_t<Callback>;
    Func func_copy{std::forward<Callback>(c)};
    auto task = pipeline(*exec, std::move(*this), std::move(func_copy));
    task.via(*exec);
    return task;
}

template <typename TYPE>
original::coroutine::task<TYPE>
original::coroutine::task<TYPE>::operator|(executor& exec)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    auto sequence = []<typename T>(executor& executor, task<T> t) mutable -> task<T> {
        T tmp = co_await t;
        co_await executor;
        co_return tmp;
    };
    auto prev_exec = this->handle_.promise().executor_;
    if (!prev_exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    auto task = sequence(exec, std::move(*this));
    task.via(*prev_exec);
    return task;
}

template <typename TYPE>
original::coroutine::task<TYPE>
original::coroutine::task<TYPE>::operator>>(executor& exec)
{
    return std::move(*this) | exec;
}

template <typename TYPE>
original::coroutine::task<TYPE>
original::coroutine::task<TYPE>::operator|(Awaiter auto&& awaiter)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    auto sequence = []<typename T>(task<T> t, Awaiter auto a) mutable -> task<T> {
        T tmp = co_await t;
        co_await a;
        co_return tmp;
    };
    auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    auto task = sequence(std::move(*this), std::forward<decltype(awaiter)>(awaiter));
    task.via(*exec);
    return task;
}

template <typename TYPE>
original::coroutine::task<TYPE>
original::coroutine::task<TYPE>::operator>>(Awaiter auto&& awaiter)
{
    return std::move(*this) | std::forward<decltype(awaiter)>(awaiter);
}

template <typename TYPE>
template <typename E, typename Handle>
original::coroutine::task<TYPE>
original::coroutine::task<TYPE>::operator|(errorCatchAwaitable<E, Handle>&& catcher)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    auto sequence = []<typename T, typename Err, typename H>(task<T> t, errorCatchAwaitable<Err, H> c) mutable -> task<T> {
        auto& h = co_await c;
        try {
            T tmp = co_await t;
            co_return tmp;
        } catch (const Err& exception) {
            co_return h(exception);
        }
    };
    auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    auto task = sequence(std::move(*this), std::forward<decltype(catcher)>(catcher));
    task.via(*exec);
    return task;
}

template <typename TYPE>
template <typename E, typename Handle>
original::coroutine::task<TYPE>
original::coroutine::task<TYPE>::operator>>(errorCatchAwaitable<E, Handle>&& catcher)
{
    return std::move(*this) | std::forward<decltype(catcher)>(catcher);
}

template <typename TYPE>
template <typename Pred, typename Then, typename Else>
auto original::coroutine::task<TYPE>::operator|(taskCondition<Pred, Then, Else>&& condition)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    using ReturnThen = std::invoke_result_t<Then>;
    using ReturnElse = std::invoke_result_t<Else>;
    staticError<valueError, !std::is_same_v<ReturnThen, ReturnElse>>::asserts();
    using Return = ReturnThen;

    auto branch = []<typename P, typename T, typename E>(taskCondition<P, T, E> cond, task t, executor* exe) -> task<Return> {
        co_await t;
        auto pred = makeTask(*exe, std::move(cond.pred_)); // NOLINT: Prevent internal error from MinGW GCC
        if (co_await pred) {
            co_return co_await makeTask(*exe, std::move(cond.then_));
        }
        co_return co_await makeTask(*exe, std::move(cond.else_));
    };

    auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    auto task = branch(std::forward<decltype(condition)>(condition), std::move(*this), exec);
    task.via(*exec);
    return task;
}

template <typename TYPE>
template <typename Pred, typename Then, typename Else>
auto original::coroutine::task<TYPE>::operator>>(taskCondition<Pred, Then, Else>&& condition)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    using ReturnThen = std::invoke_result_t<Then, TYPE>;
    using ReturnElse = std::invoke_result_t<Else, TYPE>;
    staticError<valueError, !std::is_same_v<ReturnThen, ReturnElse>>::asserts();
    using Return = ReturnThen;

    auto branch = []<typename P, typename T, typename E>(taskCondition<P, T, E> cond, task t, executor* exe) -> task<Return> {
        auto prev = co_await t;
        auto pred = makeTask(*exe, std::move(cond.pred_), prev); // NOLINT: Prevent internal error from MinGW GCC
        if (co_await pred) {
            co_return co_await makeTask(*exe, std::move(cond.then_), prev);
        }
        co_return co_await makeTask(*exe, std::move(cond.else_), prev);
    };

    auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    auto task = branch(std::forward<decltype(condition)>(condition), std::move(*this), exec);
    task.via(*exec);
    return task;
}

template <typename TYPE>
template <typename ... Args>
auto original::coroutine::task<TYPE>::operator|(taskArgs<Args...>&& args)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    const auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    auto new_args = std::move(args) | *exec;

    using bridgeType = taskArgs<Args...>::template bridge<TYPE, false>;
    return bridgeType(std::move(new_args), std::move(*this));
}

template <typename TYPE>
template <typename ... Args>
auto original::coroutine::task<TYPE>::operator>>(taskArgs<Args...>&& args)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    const auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    auto new_args = std::move(args) >> *exec;

    using bridgeType = taskArgs<Args...>::template bridge<TYPE, true>;
    return bridgeType(std::move(new_args), std::move(*this));
}

template <typename TYPE>
template <typename ... Callback>
auto original::coroutine::task<TYPE>::operator|(tuple<Callback...>&& cs)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    const auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    using TasksTuple = tuple<task<std::invoke_result_t<Callback>>...>;
    using ResultTuple = tuple<
        someType<
            std::is_void_v<std::invoke_result_t<Callback>>,
            bool,
            std::invoke_result_t<Callback>
        >
    ...>;

    auto sequence = []<typename... F>(task t, tuple<F...> funcs, executor* exe) mutable -> task<ResultTuple> {
        co_await t;
        auto make_tasks = []<u_integer... I, typename... Func>(indexSequence<I...>, tuple<Func...>& fn, executor* e) {
            return tuple{
                std::move(makeTask(*e, fn.template get<I>()))...
            };
        };
        auto tasks = make_tasks(makeSequence<sizeof...(F)>(), funcs, exe);
        auto get_results = [exe]<u_integer... I>(indexSequence<I...>, TasksTuple tp) -> task<ResultTuple> {
            auto convert_to_bool = []<typename T>(task<T>& cur) -> task<someType<std::is_void_v<T>, bool, T>> {
                if constexpr (std::is_void_v<T>) {
                    co_await cur;
                    co_return true;
                } else {
                    co_return co_await cur;
                }
            };
            co_return ResultTuple{ co_await convert_to_bool(tp.template get<I>()).via(exe)... };
        };
        auto results_tasks = get_results(makeSequence<sizeof...(F)>(), std::move(tasks));
        results_tasks.via(*exe);
        co_return co_await results_tasks;
    };
    auto task = sequence(std::move(*this), std::move(cs), exec);
    task.via(*exec);
    return task;
}

template <typename TYPE>
template <typename ... Callback>
auto original::coroutine::task<TYPE>::operator>>(tuple<Callback...>&& cs)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    const auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    using TasksTuple = tuple<task<std::invoke_result_t<Callback, TYPE>>...>;
    using ResultTuple = tuple<
        someType<
            std::is_void_v<std::invoke_result_t<Callback, TYPE>>,
            bool,
            std::invoke_result_t<Callback, TYPE>
        >
    ...>;

    auto sequence = []<typename... F>(task t, tuple<F...> funcs, executor* exe) mutable -> task<ResultTuple> {
        TYPE tmp = co_await t;
        auto make_tasks = []<u_integer... I, typename... Func, typename T>(indexSequence<I...>, tuple<Func...>& fn, executor* e, T arg) {
            return tuple{
                std::move(makeTask(*e, fn.template get<I>(), std::move(arg)))...
            };
        };
        auto tasks = make_tasks(makeSequence<sizeof...(F)>(), funcs, exe, tmp);
        auto get_results = [exe]<u_integer... I>(indexSequence<I...>, TasksTuple tp) -> task<ResultTuple> {
            auto convert_to_bool = []<typename T>(task<T>& cur) -> task<someType<std::is_void_v<T>, bool, T>> {
                if constexpr (std::is_void_v<T>) {
                    co_await cur;
                    co_return true;
                } else {
                    co_return co_await cur;
                }
            };
            co_return ResultTuple{ co_await convert_to_bool(tp.template get<I>()).via(*exe)... };
        };
        auto results_tasks = get_results(makeSequence<sizeof...(F)>(), std::move(tasks));
        results_tasks.via(*exe);
        co_return co_await results_tasks;
    };
    auto task = sequence(std::move(*this), std::move(cs), exec);
    task.via(*exec);
    return task;
}

template<typename TYPE>
TYPE original::coroutine::task<TYPE>::result() {
    if (this->empty())
        throw valueError("Can not get result from an empty task");

    auto& promise = handle_.promise();
    switch (promise.state_) {
        case state::STANDBY:
        default:
            throw sysError("Task not started");

        case state::RUNNING:
            throw sysError("Task not finished");

        case state::FINISHED:
            break;
    }
    promise.rethrow_if_exception();
    return std::move(*promise.value_);
}

template <typename TYPE>
original::coroutine::task<TYPE>::~task()
{
    if (!this->empty())
        this->handle_.destroy();
}

inline original::coroutine::task<void>::awaitable::awaitable(const handle h) : handle_(h) {}

inline bool original::coroutine::task<void>::awaitable::await_ready() const noexcept
{
    return !this->handle_ || this->handle_.done();
}

inline void original::coroutine::task<void>::awaitable::await_suspend(const std::coroutine_handle<> waiter) noexcept // NOLINT
{
    auto& promise = this->handle_.promise();
    promise.continuation_ = waiter;

    switch (promise.state_) {
    case state::STANDBY:
    default:
        promise.state_ = state::RUNNING;
    case state::RUNNING:
        if (promise.executor_)
            promise.executor_->schedule(this->handle_);
        break;
    case state::FINISHED:
        break;
    }
}

inline void original::coroutine::task<void>::awaitable::await_resume() const
{
    const auto& promise = this->handle_.promise();
    promise.rethrow_if_exception();
}

inline bool original::coroutine::task<void>::finalAwaitable::await_ready() noexcept // NOLINT
{
    return false;
}

inline void original::coroutine::task<void>::finalAwaitable::await_suspend( // NOLINT
     const std::coroutine_handle<promise_type> handle) noexcept
{
    auto& promise = handle.promise();
    promise.state_ = state::FINISHED;

    if (promise.continuation_ && promise.executor_) {
        promise.executor_->schedule(promise.continuation_);
    }

    if (const auto spt = promise.spt_) {
        spt->arrive();
    }
}

inline void original::coroutine::task<void>::finalAwaitable::await_resume() noexcept {} // NOLINT

inline original::coroutine::task<void>
original::coroutine::task<void>::promise_type::get_return_object()
{
    return task{handle::from_promise(*this)};
}

inline auto original::coroutine::task<void>::promise_type::initial_suspend() // NOLINT
{
    return std::suspend_always{};
}

inline original::coroutine::task<void>::finalAwaitable
original::coroutine::task<void>::promise_type::final_suspend() noexcept // NOLINT
{
    return finalAwaitable{};
}

inline void original::coroutine::task<void>::promise_type::return_void() {} // NOLINT

inline void original::coroutine::task<void>::promise_type::unhandled_exception()
{
    this->e_ = std::current_exception();
}

inline void original::coroutine::task<void>::promise_type::rethrow_if_exception() const
{
    if (this->e_)
        std::rethrow_exception(this->e_);
}

inline original::coroutine::task<void>::task(const handle h) : handle_(h) {}

inline void original::coroutine::task<void>::sync(syncPoint& spt) const
{
    if (this->empty())
        throw sysError("Can not sync with an empty task");
    if (this->started())
        throw sysError("Can not sync with a started task");
    this->handle_.promise().spt_ = &spt;
}

inline bool original::coroutine::task<void>::start() const noexcept {
    if (this->empty())
        return false;

    switch (auto& promise = this->handle_.promise(); promise.state_) {
        case state::STANDBY:
            if (this->hasExecutor()){
                promise.state_ = state::RUNNING;
                promise.executor_->schedule(this->handle_);
                return true;
            }
            break;
        case state::RUNNING:
        case state::FINISHED:
        default:
            break;
    }
    return false;
}

inline bool original::coroutine::task<void>::hasExecutor() const noexcept
{
    if (this->empty())
        return false;

    return this->handle_.promise().executor_;
}

inline original::coroutine::task<void>&
original::coroutine::task<void>::via(executor& executor) noexcept {
    if (this->empty())
        return *this;

    auto& promise = this->handle_.promise();
    promise.executor_ = &executor;
    return *this;
}

inline original::coroutine::task<void>::task(task&& other) noexcept
{
    this->handle_ = other.handle_;
    other.handle_ = nullptr;
}

inline original::coroutine::task<void>&
original::coroutine::task<void>::operator=(task&& other) noexcept
{
    if (this == &other)
        return *this;

    if (!this->empty())
        this->handle_.destroy();

    this->handle_ = other.handle_;
    other.handle_ = nullptr;
    return *this;
}

inline bool original::coroutine::task<void>::started() const noexcept {
    if (this->empty())
        return false;

    const auto& promise = this->handle_.promise();
    return promise.state_ != state::STANDBY;
}

inline bool original::coroutine::task<void>::finished() const noexcept
{
    if (this->empty())
        return false;

    const auto& promise = this->handle_.promise();
    return promise.state_ == state::FINISHED && this->handle_.done();
}

inline bool original::coroutine::task<void>::empty() const noexcept {
    return !this->handle_;
}

inline original::coroutine::task<void>::operator bool() const noexcept
{
    return this->handle_ != nullptr;
}

inline original::coroutine::task<void>::awaitable
original::coroutine::task<void>::operator co_await() const noexcept
{
    return awaitable{this->handle_};
}

inline void original::coroutine::task<void>::result() const
{
    if (this->empty())
        throw valueError("Can not get result from an empty task");

    const auto& promise = handle_.promise();
    switch (promise.state_) {
        case state::STANDBY:
        default:
            throw sysError("Task not started");

        case state::RUNNING:
            throw sysError("Task not finished");

        case state::FINISHED:
            break;
    }
    promise.rethrow_if_exception();
}

template <typename U>
original::coroutine::task<U>
original::coroutine::task<void>::operator|(task<U> rhs)
{
    if (this->empty() || rhs.empty())
        throw valueError("Can not combine empty tasks");

    auto sequence = []<typename LHS, typename RHS>(task<LHS> l, task<RHS> r) mutable -> task<U> {
        co_await l;
        co_return co_await r;
    };
    const auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");
    auto task = sequence(std::move(*this), std::move(rhs));
    task.via(*exec);
    return task;
}

template <typename U>
original::coroutine::task<U>
original::coroutine::task<void>::operator>>(task<U> rhs)
{
    if (this->empty() || rhs.empty())
        throw valueError("Can not combine empty tasks");

    return std::move(*this) | std::move(rhs);
}

template <typename Callback>
auto original::coroutine::task<void>::operator|(Callback&& c)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    const auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    using Func  = std::decay_t<Callback>;
    Func func_copy{std::forward<Callback>(c)};
    return std::move(*this) | std::move(makeTask(*exec, std::move(func_copy)));
}

template <typename Callback>
auto original::coroutine::task<void>::operator>>(Callback&& c)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    const auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    using Func  = std::decay_t<Callback>;
    Func func_copy{std::forward<Callback>(c)};
    return std::move(*this) >> std::move(makeTask(*exec, std::move(func_copy)));
}

inline original::coroutine::task<void>
original::coroutine::task<void>::operator|(executor& exec)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    auto sequence = [](executor& executor, task t) mutable -> task {
        co_await t;
        co_await executor;
        co_return;
    };
    const auto prev_exec = this->handle_.promise().executor_;
    if (!prev_exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    auto task = sequence(exec, std::move(*this));
    task.via(*prev_exec);
    return task;
}

inline original::coroutine::task<void>
original::coroutine::task<void>::operator>>(executor& exec)
{
    return std::move(*this) | exec;
}

original::coroutine::task<void>
original::coroutine::task<void>::operator|(Awaiter auto&& awaiter)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    auto sequence = [](task t, Awaitable auto a) mutable -> task {
        co_await t;
        co_await a;
        co_return;
    };
    auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    auto task = sequence(std::move(*this), std::forward<decltype(awaiter)>(awaiter));
    task.via(*exec);
    return task;
}

original::coroutine::task<void>
original::coroutine::task<void>::operator>>(Awaiter auto&& awaiter)
{
    return std::move(*this) | std::forward<decltype(awaiter)>(awaiter);
}

template <typename E, typename Handle>
original::coroutine::task<void>
original::coroutine::task<void>::operator|(errorCatchAwaitable<E, Handle>&& catcher)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    auto sequence = []<typename Err, typename H>(task t, errorCatchAwaitable<Err, H> c) mutable -> task {
        auto& h = co_await c;
        try {
            co_await t;
            co_return;
        } catch (const Err& exception) {
            co_return h(exception);
        }
    };
    auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    auto task = sequence(std::move(*this), std::forward<decltype(catcher)>(catcher));
    task.via(*exec);
    return task;
}

template <typename E, typename Handle>
original::coroutine::task<void>
original::coroutine::task<void>::operator>>(errorCatchAwaitable<E, Handle>&& catcher)
{
    return std::move(*this) | std::forward<decltype(catcher)>(catcher);
}

template <typename Pred, typename Then, typename Else>
auto original::coroutine::task<void>::operator|(taskCondition<Pred, Then, Else>&& condition)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    using ReturnThen = std::invoke_result_t<Then>;
    using ReturnElse = std::invoke_result_t<Else>;
    staticError<valueError, !std::is_same_v<ReturnThen, ReturnElse>>::asserts();
    using Return = ReturnThen;

    auto branch = []<typename P, typename T, typename E>(taskCondition<P, T, E> cond, task t, executor* exe) -> task<Return> {
        co_await t;
        auto pred = makeTask(*exe, std::move(cond.pred_)); // NOLINT: Prevent internal error from MinGW GCC
        if (co_await pred) {
            co_return co_await makeTask(*exe, std::move(cond.then_));
        }
        co_return co_await makeTask(*exe, std::move(cond.else_));
    };

    auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    auto task = branch(std::forward<decltype(condition)>(condition), std::move(*this), exec);
    task.via(*exec);
    return task;
}

template <typename Pred, typename Then, typename Else>
auto original::coroutine::task<void>::operator>>(taskCondition<Pred, Then, Else>&& condition)
{
    return std::move(*this) | std::forward<decltype(condition)>(condition);
}

template <typename ... Callback>
auto original::coroutine::task<void>::operator|(tuple<Callback...>&& cs)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    const auto exec = this->handle_.promise().executor_;
    if (!exec)
        throw sysError("Tasks without a specified executor cannot be combined");

    using TasksTuple = tuple<task<std::invoke_result_t<Callback>>...>;
    using ResultTuple = tuple<
        someType<
            std::is_void_v<std::invoke_result_t<Callback>>,
            bool,
            std::invoke_result_t<Callback>
        >
    ...>;

    auto sequence = []<typename... F>(task t, tuple<F...> funcs, executor* exe) mutable -> task<ResultTuple> {
        co_await t;
        auto make_tasks = []<u_integer... I, typename... Func>(indexSequence<I...>, tuple<Func...>& fn, executor* e) {
            return tuple{
                std::move(makeTask(*e, fn.template get<I>()))...
            };
        };
        auto tasks = make_tasks(makeSequence<sizeof...(F)>(), funcs, exe);
        auto get_results = [exe]<u_integer... I>(indexSequence<I...>, TasksTuple tp) -> task<ResultTuple> {
            auto convert_to_bool = []<typename T>(task<T>& cur) -> task<someType<std::is_void_v<T>, bool, T>> {
                if constexpr (std::is_void_v<T>) {
                    co_await cur;
                    co_return true;
                } else {
                    co_return co_await cur;
                }
            };
            co_return ResultTuple{ co_await convert_to_bool(tp.template get<I>()).via(*exe)... };
        };
        auto results_tasks = get_results(makeSequence<sizeof...(F)>(), std::move(tasks));
        results_tasks.via(*exe);
        co_return co_await results_tasks;
    };
    auto task = sequence(std::move(*this), std::move(cs), exec);
    task.via(*exec);
    return task;
}

template <typename ... Callback>
auto original::coroutine::task<void>::operator>>(tuple<Callback...>&& cs)
{
    return std::move(*this) | std::forward<decltype(cs)>(cs);
}

inline original::coroutine::task<void>::~task()
{
    if (!this->empty())
        this->handle_.destroy();
}

template <typename Callback, typename ... Args>
auto original::coroutine::makeTask(Callback&& c, Args&&... args)
    -> task<std::invoke_result_t<Callback, Args...>>
{
    using Return = std::invoke_result_t<Callback, Args...>;
    using Func  = std::decay_t<Callback>;
    using Tuple = std::tuple<std::decay_t<Args>...>;

    Func func_copy{std::forward<Callback>(c)};
    Tuple args_copy{std::forward<Args>(args)...};
    auto run_impl = [](Func f, Tuple tup) -> task<Return>
    {
        co_return std::apply(std::move(f), std::move(tup));
    };
    auto t = run_impl(std::move(func_copy), std::move(args_copy));
    return t;
}

template<typename Callback, typename... Args>
auto original::coroutine::makeTask(executor& executor, Callback&& c, Args&&... args)
     -> task<std::invoke_result_t<Callback, Args...>> {
    using Return = std::invoke_result_t<Callback, Args...>;
    task<Return> t = makeTask(std::forward<Callback>(c), std::forward<Args>(args)...);
    t.via(executor);
    return t;
}

template <typename Callback, typename ... Args>
auto original::coroutine::makeTask(Callback&& c, tuple<Args...> args)
    -> task<std::invoke_result_t<Callback, Args...>>
{
    return apply(
               [&](auto&&... unpacked) {
                   return makeTask(std::forward<Callback>(c), std::move(unpacked)...);
               },
               std::move(args)
           );
}

template <typename Callback, typename ... Args>
auto original::coroutine::makeTask(executor& executor, Callback&& c, tuple<Args...> args)
    -> task<std::invoke_result_t<Callback, Args...>>
{
    using Return = std::invoke_result_t<Callback, Args...>;
    task<Return> t = makeTask(std::forward<Callback>(c), std::move(args));
    t.via(executor);
    return t;
}

template <typename TYPE>
TYPE original::coroutine::spinRun(task<TYPE> t)
{
    if (t.empty())
        throw valueError("Can not run an empty task");
    if (t.finished())
        return t.result();
    if (t.started())
        throw valueError("Can not run a task while started");
    if (!t.hasExecutor())
        throw valueError("Can not run a task without a specified executor");

    t.start();
    u_integer spin = 0;
    while (!t.finished()) {
        if (spin < 50) {
            thread::yield();
        } else if (spin < 200) {
            thread::sleep(microseconds(50));
        } else {
            thread::sleep(milliseconds(1));
        }
        spin += 1;
    }
    return t.result();
}

template <typename TYPE>
TYPE original::coroutine::run(task<TYPE> t)
{
    if (t.empty())
        throw valueError("Can not run an empty task");
    if (t.finished())
        return t.result();
    if (t.started())
        throw valueError("Can not run a task while started");
    if (!t.hasExecutor())
        throw valueError("Can not run a task without a specified executor");

    syncPoint pt{2};
    t.sync(pt);
    if (const bool started = t.start(); !started) {
        throw sysError("Can not run a task");
    }
    pt.arrive();
    return t.result();
}

inline bool original::coroutine::run(const task<void>& t)
{
    if (t.empty())
        throw valueError("Can not run an empty task");
    if (t.finished())
        return true;
    if (t.started())
        throw valueError("Can not run a task while started");
    if (!t.hasExecutor())
        throw valueError("Can not run a task without a specified executor");

    syncPoint pt{2};
    t.sync(pt);
    if (const bool started = t.start(); !started) {
        return false;
    }
    pt.arrive();
    return true;
}

template <typename ... Args>
original::tuple<original::someType<std::is_void_v<Args>, bool, Args>...>
original::coroutine::whenAll(task<Args>... ts)
{
    if ((ts.empty() || ...)) {
        throw valueError("Can not use whenAll with empty tasks");
    }

    if (const bool all_have_executor = (ts.hasExecutor() && ...); !all_have_executor) {
        throw sysError("All tasks must have a specified executor for whenAll");
    }

    if ((ts.started() || ...)) {
        throw valueError("Can not use whenAll with already started tasks");
    }

    syncPoint pt{sizeof...(ts) + 1};
    (ts.sync(pt), ...);
    if (const bool all_started = (ts.start() && ...); !all_started) {
        throw sysError("Failed to start one or more tasks");
    }
    pt.arrive();

    return original::tuple<someType<std::is_void_v<Args>, bool, Args>...> {
        []<typename T>(task<T>& t) -> someType<std::is_void_v<T>, bool, T> {
            if constexpr (std::is_void_v<T>) {
                t.result();
                return true;
            } else {
                return t.result();
            }
        }(ts)...
    };
}

template <typename ... Args>
original::tuple<original::someType<std::is_void_v<Args>, bool, Args>...>
original::coroutine::spinWhenAll(task<Args>... ts)
{
    if ((ts.empty() || ...)) {
        throw valueError("Can not use spinWhenAll with empty tasks");
    }
    if (const bool all_have_executor = (ts.hasExecutor() && ...); !all_have_executor) {
        throw sysError("All tasks must have a specified executor for spinWhenAll");
    }
    if ((ts.started() || ...)) {
        throw valueError("Can not use spinWhenAll with already started tasks");
    }
    if (const bool all_started = (ts.start() && ...); !all_started) {
        throw sysError("Failed to start one or more tasks");
    }

    u_integer spin = 0;
    while (!(ts.finished() && ...)) {
        if (spin < 50) {
            thread::yield();
        } else if (spin < 200) {
            thread::sleep(microseconds(50));
        } else {
            thread::sleep(milliseconds(1));
        }
        spin += 1;
    }

    return original::tuple<someType<std::is_void_v<Args>, bool, Args>...>{
        []<typename T>(task<T>& t) -> someType<std::is_void_v<T>, bool, T> {
            if constexpr (std::is_void_v<T>) {
                t.result();
                return true;
            } else {
                return t.result();
            }
        }(ts)...
    };
}

template <typename Callback>
auto original::operator|(executor& exec, Callback&& c)
{
    return coroutine::makeTask(exec, std::forward<Callback>(c));
}

template <typename Callback>
auto original::operator>>(executor& exec, Callback&& c)
{
    return exec | std::forward<Callback>(c);
}

template <typename ... Callback>
auto original::operator|(executor& exec, tuple<Callback...>&& cs)
{
    return coroutine::makeTask(exec, []{}) | std::forward<tuple<Callback...>>(cs);
}

template <typename ... Callback>
auto original::operator>>(executor& exec, tuple<Callback...>&& cs)
{
    return exec | std::forward<tuple<Callback...>>(cs);
}

template <typename ... Args>
original::coroutine::taskArgs<Args...> original::coBind(Args&&... args)
{
    using TupleType = tuple<std::decay_t<Args>...>;
    return coroutine::taskArgs<std::decay_t<Args>...>{
        TupleType{ std::forward<Args>(args)... }
    };
}

template <typename ... Args>
original::coroutine::taskArgs<Args...>
original::operator|(executor& executor, coroutine::taskArgs<Args...>&& args)
{
    return std::move(args) | executor;
}

template <typename ... Args>
original::coroutine::taskArgs<Args...>
original::operator>>(executor& executor, coroutine::taskArgs<Args...>&& args)
{
    return std::move(args) | executor;
}

template <typename ... Callback>
original::tuple<std::decay_t<Callback>...>
original::coParallel(Callback&&... c)
{
    return tuple<std::decay_t<Callback>...>{std::decay_t<Callback>(std::forward<Callback>(c))...};
}

template <typename Pred, typename Then, typename Else>
auto original::coIfElse(Pred&& p, Then&& t, Else&& e)
{
    using ConditionType = coroutine::taskCondition<
        std::decay_t<Pred>,
        std::decay_t<Then>,
        std::decay_t<Else>
    >;
    return ConditionType{std::forward<Pred>(p), std::forward<Then>(t), std::forward<Else>(e)};
}

#endif //ORIGINAL_COROUTINES_H
