#ifndef ORIGINAL_COROUTINES_H
#define ORIGINAL_COROUTINES_H
#include "optional.h"
#include "executor.h"
#include <coroutine>
#include <exception>

/**
 * @file coroutines.h
 * @brief C++20 coroutine support with generator pattern implementation
 *
 * This file implements a type-safe, lazy-evaluation generator pattern using
 * C++20 coroutines. The generator provides a convenient way to create and
 * consume sequences of values with minimal memory overhead and efficient
 * suspension/resumption semantics.
 *
 * Key Features:
 * - Lazy evaluation: Values are generated on-demand
 * - Exception safety: Proper exception propagation through coroutine boundaries
 * - Iterator support: Compatible with range-based for loops and STL algorithms
 * - Move semantics: Efficient transfer of coroutine state
 * - Resource management: Automatic cleanup of coroutine handles
 * - Type safety: Compile-time type checking for generated values
 *
 * @note The generator suspends after each yielded value, allowing consumers
 *       to control the execution flow and memory usage.
 * @note Coroutine state is automatically destroyed when the generator goes
 *       out of scope, preventing resource leaks.
 */

namespace original {
    /**
     * @class coroutine
     * @brief Namespace for coroutine-related utilities and generator implementation
     * @details Provides a generator class template that implements the C++20 coroutine
     *          protocol for creating lazy sequences of values.
     */
    class coroutine {
    public:
        /**
         * @class generator
         * @tparam TYPE Type of values generated by the coroutine
         * @brief Lazy sequence generator using C++20 coroutines
         * @details Implements the coroutine promise protocol to create generators
         *          that can yield sequences of values. Supports range-based for loops,
         *          manual iteration, and exception propagation.
         *
         * The generator maintains the following states:
         * - Suspended: Waiting to be resumed (initial and after each yield)
         * - Running: Currently executing coroutine logic
         * - Completed: All values have been generated
         *
         * @note Generators are move-only types to prevent accidental copying of
         *       coroutine state.
         * @note Iterators become invalid when the generator is destroyed or moved.
         */
        template<typename TYPE>
        class generator {
        public:
            struct promise_type;
        private:
            using handle = std::coroutine_handle<promise_type>;  ///< Coroutine handle type

            handle handle_;  ///< Underlying coroutine handle

        public:
            /**
             * @struct promise_type
             * @brief Implements the coroutine promise interface for generator
             * @details Manages the coroutine state, value storage, and exception
             *          handling according to the C++20 coroutine specification.
             */
            struct promise_type {
                bool initial_status = false;      ///< Tracks if coroutine has started execution
                alternative<TYPE> value_;        ///< Storage for the current yielded value
                std::exception_ptr e_;           ///< Captured exceptions for propagation

                /**
                 * @brief Creates the generator object from this promise
                 * @return generator instance associated with this promise
                 */
                generator get_return_object();

                /**
                 * @brief Defines initial suspension behavior
                 * @return suspend_always to start in suspended state
                 * @note Lazy initialization: coroutine starts suspended
                 */
                static std::suspend_always initial_suspend();

                /**
                 * @brief Defines final suspension behavior
                 * @return suspend_always to keep frame alive for cleanup
                 * @note Prevents automatic destruction of coroutine frame
                 */
                static std::suspend_always final_suspend() noexcept;

                /**
                 * @brief Handles coroutine completion without value
                 */
                static void return_void();

                /**
                 * @brief Handles value yielding from coroutine
                 * @param value Value to yield to caller
                 * @return suspend_always to suspend after yielding
                 * @note Stores the value and suspends execution
                 */
                std::suspend_always yield_value(TYPE value);

                /**
                 * @brief Captures exceptions thrown from coroutine
                 */
                void unhandled_exception();

                /**
                 * @brief Re-throws any captured exception
                 * @throws The exception previously captured by unhandled_exception
                 */
                void rethrow_if_exception() const;
            };

            /**
             * @class iterator
             * @brief Input iterator for generator range-based operations
             * @details Provides input iterator interface for using generator
             *          with range-based for loops and STL algorithms.
             *
             * Iterator invalidation:
             * - Invalidated when generator is destroyed
             * - Invalidated when generator is moved from
             * - Safe for single-pass algorithms only
             */
            class iterator {
                generator* gen_;  ///< Pointer to parent generator
                bool end_;        ///< Flag indicating end iterator

                /**
                 * @brief Default constructor creates end iterator
                 */
                iterator();

                /**
                 * @brief Constructs iterator for specific generator
                 * @param gen Pointer to generator to iterate over
                 */
                explicit iterator(generator* gen);
            public:
                friend coroutine;

                /**
                 * @brief Advances iterator to next value
                 * @return Reference to this iterator
                 * @note Calls generator::next() internally
                 */
                iterator& operator++();

                /**
                 * @brief Dereferences iterator to get current value
                 * @return Current value from generator
                 * @throws nullPointerError if dereferencing end iterator
                 */
                TYPE operator*();

                /**
                 * @brief Checks iterator inequality
                 * @param other Iterator to compare with
                 * @return true if iterators are not equal
                 */
                bool operator!=(const iterator& other) const;

                /**
                 * @brief Checks iterator equality
                 * @param other Iterator to compare with
                 * @return true if iterators are equal
                 */
                bool operator==(const iterator& other) const;
            };

            generator(const generator&) = delete;            ///< Copy constructor deleted
            generator& operator=(const generator&) = delete; ///< Copy assignment deleted

            /**
             * @brief Move constructor transfers coroutine ownership
             * @param other Generator to move from
             * @note Source generator becomes empty after move
             */
            generator(generator&& other) noexcept;

            /**
             * @brief Move assignment operator transfers coroutine ownership
             * @param other Generator to move from
             * @return Reference to this generator
             * @note Destroys current coroutine handle before transfer
             */
            generator& operator=(generator&& other) noexcept;

            generator() = default;  ///< Default constructor creates empty generator

            /**
             * @brief Constructs generator from coroutine handle
             * @param h Coroutine handle to manage
             */
            explicit generator(handle h);

            /**
             * @brief Gets begin iterator for range-based operations
             * @return Iterator positioned at first value
             * @note Resumes coroutine to get first value
             */
            iterator begin();

            /**
             * @brief Gets end iterator for range-based operations
             * @return End iterator marker
             */
            static iterator end();

            /**
             * @brief Checks if coroutine has been launched
             * @return true if coroutine has started execution
             */
            [[nodiscard]] bool launched() const;

            /**
             * @brief Checks if generator has more values
             * @return true if next() would return a value
             */
            [[nodiscard]] bool hasNext() const;

            /**
             * @brief Peeks at current value without advancing
             * @return optional containing current value if available
             * @note Does not resume coroutine or change state
             */
            [[nodiscard]] alternative<TYPE> peek() const;

            /**
             * @brief Advances generator and gets next value
             * @return optional containing next value if available
             * @note Resumes coroutine execution and may throw exceptions
             */
            alternative<TYPE> next();

            /**
             * @brief Destructor cleans up coroutine resources
             * @note Automatically destroys coroutine handle
             */
            ~generator();
        };

        template<typename TYPE>
        class task {
        public:
            friend coroutine;
            struct promise_type;
        private:
            enum class state {
                STANDBY,
                RUNNING,
                FINISHED,
            };

            using handle = std::coroutine_handle<promise_type>;

            handle handle_;
        public:
            struct awaitable {
                handle handle_;

                explicit awaitable(handle h);

                [[nodiscard]] bool await_ready() const noexcept;

                void await_suspend(std::coroutine_handle<> waiter) noexcept;

                TYPE await_resume() const noexcept;
            };

            struct finalAwaitable {
                bool await_ready() noexcept;

                void await_suspend(handle handle) noexcept;

                void await_resume() noexcept;
            };

            struct promise_type {
                std::coroutine_handle<> continuation_{};
                executor* executor_ = nullptr;
                executor* next_exec_ = nullptr;
                alternative<TYPE> value_;
                std::exception_ptr e_;
                state state_ = state::STANDBY;

                task get_return_object();

                auto initial_suspend();

                finalAwaitable final_suspend() noexcept;

                void return_value(TYPE value);

                void unhandled_exception();

                void rethrow_if_exception() const;
            };

            task(const task&) = delete;
            task& operator=(const task&) = delete;

            task() = default;

            explicit task(handle h);

            bool start() noexcept;

            [[nodiscard]] bool hasExecutor() const noexcept;

            task& via(executor& executor) noexcept;

            task& viaNext(executor& executor) noexcept;

            task(task&& other) noexcept;

            task& operator=(task&& other) noexcept;

            [[nodiscard]] bool started() const noexcept;

            [[nodiscard]] bool finished() const noexcept;

            [[nodiscard]] bool empty() const noexcept;

            [[nodiscard]] explicit operator bool() const noexcept;

            awaitable operator co_await() noexcept;

            template<typename U>
            task<U> operator|(task<U> rhs);

            template<typename U>
            task<U> operator>>(task<U> rhs);

            template<typename Callback>
            auto operator|(Callback&& c);

            template<typename Callback>
            auto operator>>(Callback&& c);

            TYPE result();

            ~task();
        };

        template<typename Callback, typename... Args>
        static auto makeTask(executor& executor, Callback&& c, Args&&... args) -> task<std::invoke_result_t<Callback, Args...>>;
    };

    template<>
    class coroutine::task<void> {
    public:
        friend coroutine;
        struct promise_type;
    private:
        enum class state {
            STANDBY,
            RUNNING,
            FINISHED,
        };

        using handle = std::coroutine_handle<promise_type>;

        handle handle_;
    public:
        struct awaitable {
            handle handle_;

            explicit awaitable(handle h);

            [[nodiscard]] bool await_ready() const noexcept;

            void await_suspend(std::coroutine_handle<> waiter) noexcept;

            void await_resume() const noexcept;
        };

        struct finalAwaitable {
            bool await_ready() noexcept;

            void await_suspend(handle handle) noexcept;

            void await_resume() noexcept;
        };

        struct promise_type {
            std::coroutine_handle<> continuation_;
            executor* executor_ = nullptr;
            executor* next_exec_ = nullptr;
            std::exception_ptr e_;
            state state_ = state::STANDBY;

            task get_return_object();

            auto initial_suspend();

            finalAwaitable final_suspend() noexcept;

            void return_void();

            void unhandled_exception();

            void rethrow_if_exception() const;
        };

        task(const task&) = delete;
        task& operator=(const task&) = delete;

        task() = default;

        explicit task(handle h);

        [[nodiscard]] bool start() const noexcept;

        [[nodiscard]] bool hasExecutor() const noexcept;

        task& via(executor& executor) noexcept;

        task& viaNext(executor& executor) noexcept;

        task(task&& other) noexcept;

        task& operator=(task&& other) noexcept;

        [[nodiscard]] bool started() const noexcept;

        [[nodiscard]] bool finished() const noexcept;

        [[nodiscard]] bool empty() const noexcept;

        [[nodiscard]] explicit operator bool() const noexcept;

        awaitable operator co_await() const noexcept;

        void result() const;

        template<typename U>
        task<U> operator|(task<U> rhs);

        template<typename U>
        task<U> operator>>(task<U> rhs);

        template<typename Callback>
        auto operator|(Callback&& c);

        template<typename Callback>
        auto operator>>(Callback&& c);

        ~task();
    };
}

template <typename TYPE>
original::coroutine::generator<TYPE>
original::coroutine::generator<TYPE>::promise_type::get_return_object()
{
    return generator{handle::from_promise(*this)};
}

template <typename TYPE>
std::suspend_always original::coroutine::generator<TYPE>::promise_type::initial_suspend()
{
    return std::suspend_always{};
}

template <typename TYPE>
std::suspend_always original::coroutine::generator<TYPE>::promise_type::final_suspend() noexcept
{
    return std::suspend_always{};
}

template <typename TYPE>
void original::coroutine::generator<TYPE>::promise_type::return_void() {}

template <typename TYPE>
std::suspend_always original::coroutine::generator<TYPE>::promise_type::yield_value(TYPE value)
{
    if (!this->initial_status) {
        this->initial_status = true;
    }
    this->value_ = std::move(value);
    return std::suspend_always{};
}

template <typename TYPE>
void original::coroutine::generator<TYPE>::promise_type::unhandled_exception()
{
    this->e_ = std::current_exception();
}

template <typename TYPE>
void original::coroutine::generator<TYPE>::promise_type::rethrow_if_exception() const
{
    if (this->e_)
        std::rethrow_exception(this->e_);
}

template <typename TYPE>
original::coroutine::generator<TYPE>::iterator::iterator() : gen_(nullptr), end_(true) {}

template <typename TYPE>
original::coroutine::generator<TYPE>::iterator::iterator(generator* gen) : gen_(gen), end_(false)
{
    if (!this->gen_) {
        this->end_ = true;
        return;
    }
    ++*this;
}

template <typename TYPE>
original::coroutine::generator<TYPE>::iterator&
original::coroutine::generator<TYPE>::iterator::operator++()
{
    if (this->end_)
        return *this;
    if (auto gen_next = this->gen_->next(); !gen_next) {
        this->end_ = true;
    }
    return *this;
}

template <typename TYPE>
TYPE original::coroutine::generator<TYPE>::iterator::operator*()
{
    if (this->end_)
        throw nullPointerError("Dereferencing end iterator");
    return *this->gen_->peek();
}

template <typename TYPE>
bool original::coroutine::generator<TYPE>::iterator::operator!=(const iterator& other) const
{
    return !(*this == other);
}

template <typename TYPE>
bool original::coroutine::generator<TYPE>::iterator::operator==(const iterator& other) const
{
    if (this->end_ && other.end_)
        return true;
    if (this->end_ != other.end_)
        return false;
    return this->gen_ == other.gen_;
}

template <typename TYPE>
original::coroutine::generator<TYPE>::generator(generator&& other) noexcept
{
    this->handle_ = other.handle_;
    other.handle_ = nullptr;
}

template <typename TYPE>
original::coroutine::generator<TYPE>&
original::coroutine::generator<TYPE>::operator=(generator&& other) noexcept
{
    if (this == &other) {
        return *this;
    }

    if (this->handle_) {
        this->handle_.destroy();
    }

    this->handle_ = other.handle_;
    other.handle_ = nullptr;
    return *this;
}

template <typename TYPE>
original::coroutine::generator<TYPE>::generator(handle h) : handle_(std::move(h)) {}

template <typename TYPE>
original::coroutine::generator<TYPE>::iterator
original::coroutine::generator<TYPE>::begin()
{
    return iterator{this};
}

template <typename TYPE>
original::coroutine::generator<TYPE>::iterator
original::coroutine::generator<TYPE>::end()
{
    return iterator{};
}

template <typename TYPE>
bool original::coroutine::generator<TYPE>::launched() const
{
    return this->handle_.promise().initial_status;
}

template <typename TYPE>
bool original::coroutine::generator<TYPE>::hasNext() const
{
    return this->handle_ && !this->handle_.done();
}

template <typename TYPE>
original::alternative<TYPE> original::coroutine::generator<TYPE>::peek() const
{
    return this->handle_.promise().value_;
}

template <typename TYPE>
original::alternative<TYPE>
original::coroutine::generator<TYPE>::next()
{
    if (!this->hasNext())
        return alternative<TYPE>{};

    this->handle_.resume();
    this->handle_.promise().rethrow_if_exception();

    if (!this->hasNext())
        return alternative<TYPE>{};

    return this->handle_.promise().value_;
}

template <typename TYPE>
original::coroutine::generator<TYPE>::~generator()
{
    if (this->handle_)
        this->handle_.destroy();
}

template <typename TYPE>
original::coroutine::task<TYPE>::awaitable::awaitable(handle h) : handle_(h) {}

template <typename TYPE>
bool original::coroutine::task<TYPE>::awaitable::await_ready() const noexcept
{
    return !this->handle_ || this->handle_.done();
}

template <typename TYPE>
void original::coroutine::task<TYPE>::awaitable::await_suspend(std::coroutine_handle<> waiter) noexcept
{
    auto& promise = this->handle_.promise();
    promise.continuation_ = waiter;

    switch (promise.state_) {
        case state::STANDBY:
        default:
            promise.state_ = state::RUNNING;
        case state::RUNNING:
            if (promise.executor_)
                promise.executor_->schedule(this->handle_);
            break;
        case state::FINISHED:
            if (promise.next_exec_)
                promise.next_exec_->schedule(waiter);
            break;
    }
}

template <typename TYPE>
TYPE original::coroutine::task<TYPE>::awaitable::await_resume() const noexcept
{
    auto& promise = this->handle_.promise();
    promise.rethrow_if_exception();
    return std::move(*promise.value_);
}

template<typename TYPE>
bool original::coroutine::task<TYPE>::finalAwaitable::await_ready() noexcept // NOLINT
{
    return false;
}

template<typename TYPE>
void original::coroutine::task<TYPE>::finalAwaitable::await_suspend(
     std::coroutine_handle<promise_type> handle) noexcept
{
    auto& promise = handle.promise();
    promise.state_ = state::FINISHED;

    if (promise.continuation_) {
        if (promise.next_exec_) {
            promise.next_exec_->schedule(promise.continuation_);
        } else if (promise.executor_) {
            promise.executor_->schedule(promise.continuation_);
        }
    }
}

template<typename TYPE>
void original::coroutine::task<TYPE>::finalAwaitable::await_resume() noexcept {} // NOLINT

template <typename TYPE>
original::coroutine::task<TYPE>
original::coroutine::task<TYPE>::promise_type::get_return_object()
{
    return task{handle::from_promise(*this)};
}

template <typename TYPE>
auto original::coroutine::task<TYPE>::promise_type::initial_suspend() // NOLINT
{
    return std::suspend_always{};
}

template <typename TYPE>
original::coroutine::task<TYPE>::finalAwaitable
original::coroutine::task<TYPE>::promise_type::final_suspend() noexcept
{
    return finalAwaitable{};
}

template <typename TYPE>
void original::coroutine::task<TYPE>::promise_type::return_value(TYPE value)
{
    this->value_ = std::move(value);
}

template <typename TYPE>
void original::coroutine::task<TYPE>::promise_type::unhandled_exception()
{
    this->e_ = std::current_exception();
}

template <typename TYPE>
void original::coroutine::task<TYPE>::promise_type::rethrow_if_exception() const
{
    if (this->e_)
        std::rethrow_exception(this->e_);
}

template <typename TYPE>
original::coroutine::task<TYPE>::task(handle h) : handle_(h) {}

template<typename TYPE>
bool original::coroutine::task<TYPE>::start() noexcept {
    if (this->empty())
        return false;

    auto& promise = this->handle_.promise();
    switch (promise.state_) {
        case state::STANDBY:
            if (this->hasExecutor()){
                promise.state_ = state::RUNNING;
                promise.executor_->schedule(this->handle_);
                return true;
            }
            break;
        case state::RUNNING:
        case state::FINISHED:
        default:
            break;
    }
    return false;
}

template <typename TYPE>
bool original::coroutine::task<TYPE>::hasExecutor() const noexcept
{
    if (this->empty())
        return false;

    return this->handle_.promise().executor_;
}

template<typename TYPE>
original::coroutine::task<TYPE>&
original::coroutine::task<TYPE>::via(executor& executor) noexcept {
    if (this->empty())
        return *this;

    auto& promise = this->handle_.promise();
    promise.executor_ = &executor;
    return *this;
}

template <typename TYPE>
original::coroutine::task<TYPE>&
original::coroutine::task<TYPE>::viaNext(executor& executor) noexcept
{
    if (this->empty())
        return *this;

    auto& promise = this->handle_.promise();
    promise.next_exec_ = &executor;
    return *this;
}

template <typename TYPE>
original::coroutine::task<TYPE>::task(task&& other) noexcept
{
    this->handle_ = other.handle_;
    other.handle_ = nullptr;
}

template <typename TYPE>
original::coroutine::task<TYPE>&
original::coroutine::task<TYPE>::operator=(task&& other) noexcept
{
    if (this == &other)
        return *this;

    if (!this->empty())
        this->handle_.destroy();

    this->handle_ = other.handle_;
    other.handle_ = nullptr;
    return *this;
}

template<typename TYPE>
bool original::coroutine::task<TYPE>::started() const noexcept {
    if (this->empty())
        return false;

    auto& promise = this->handle_.promise();
    return promise.state_ != state::STANDBY;
}

template <typename TYPE>
bool original::coroutine::task<TYPE>::finished() const noexcept
{
    if (this->empty())
        return false;

    auto& promise = this->handle_.promise();
    return promise.state_ == state::FINISHED && this->handle_.done();
}

template<typename TYPE>
bool original::coroutine::task<TYPE>::empty() const noexcept {
    return !this->handle_;
}

template <typename TYPE>
original::coroutine::task<TYPE>::operator bool() const noexcept
{
    return this->handle_ != nullptr;
}

template <typename TYPE>
original::coroutine::task<TYPE>::awaitable
original::coroutine::task<TYPE>::operator co_await() noexcept
{
    return awaitable{this->handle_};
}

template <typename TYPE>
template <typename U>
original::coroutine::task<U>
original::coroutine::task<TYPE>::operator|(task<U> rhs)
{
    if (this->empty() || rhs.empty())
        throw valueError("Can not combine empty tasks");

    auto sequence = []<typename LHS, typename RHS>(task<LHS> l, task<RHS> r) mutable -> task<U> {
        co_await l;
        co_return co_await r;
    };
    return sequence(std::move(*this), std::move(rhs));
}

template <typename TYPE>
template <typename U>
original::coroutine::task<U>
original::coroutine::task<TYPE>::operator>>(task<U> rhs)
{
    if (this->empty() || rhs.empty())
        throw valueError("Can not combine empty tasks");

    auto pipeline = []<typename LHS, typename RHS>(task<LHS> l, task<RHS> r) mutable -> task<U> {
        LHS tmp = co_await l;
        co_return co_await r(std::move(tmp));
    };
    return pipeline(std::move(*this), std::move(rhs));
}

template <typename TYPE>
template <typename Callback>
auto original::coroutine::task<TYPE>::operator|(Callback&& c)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    auto exec = this->handle_.promise().executor_;
    return std::move(*this) | std::move(makeTask(*exec, std::forward<Callback>(c)));
}

template <typename TYPE>
template <typename Callback>
auto original::coroutine::task<TYPE>::operator>>(Callback&& c)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    auto exec = this->handle_.promise().executor_;
    return std::move(*this) >> std::move(makeTask(*exec, std::forward<Callback>(c)));
}

template<typename TYPE>
TYPE original::coroutine::task<TYPE>::result() {
    if (this->empty())
        throw valueError("Can not get result from an empty task");

    auto& promise = handle_.promise();
    switch (promise.state_) {
        case state::STANDBY:
        default:
            throw sysError("Task not started");

        case state::RUNNING:
            throw sysError("Task not finished");

        case state::FINISHED:
            break;
    }
    promise.rethrow_if_exception();
    return std::move(*promise.value_);
}

template <typename TYPE>
original::coroutine::task<TYPE>::~task()
{
    if (!this->empty())
        this->handle_.destroy();
}

inline original::coroutine::task<void>::awaitable::awaitable(const handle h) : handle_(h) {}

inline bool original::coroutine::task<void>::awaitable::await_ready() const noexcept
{
    return !this->handle_ || this->handle_.done();
}

inline void original::coroutine::task<void>::awaitable::await_suspend(const std::coroutine_handle<> waiter) noexcept // NOLINT
{
    auto& promise = this->handle_.promise();
    promise.continuation_ = waiter;

    switch (promise.state_) {
    case state::STANDBY:
    default:
        promise.state_ = state::RUNNING;
    case state::RUNNING:
        if (promise.executor_)
            promise.executor_->schedule(this->handle_);
        break;
    case state::FINISHED:
        if (promise.next_exec_)
            promise.next_exec_->schedule(waiter);
        break;
    }
}

inline void original::coroutine::task<void>::awaitable::await_resume() const noexcept
{
    const auto& promise = this->handle_.promise();
    promise.rethrow_if_exception();
}

inline bool original::coroutine::task<void>::finalAwaitable::await_ready() noexcept // NOLINT
{
    return false;
}

inline void original::coroutine::task<void>::finalAwaitable::await_suspend( // NOLINT
     const std::coroutine_handle<promise_type> handle) noexcept
{
    auto& promise = handle.promise();
    promise.state_ = state::FINISHED;

    if (promise.continuation_) {
        if (promise.next_exec_) {
            promise.next_exec_->schedule(promise.continuation_);
        } else if (promise.executor_) {
            promise.executor_->schedule(promise.continuation_);
        }
    }
}

inline void original::coroutine::task<void>::finalAwaitable::await_resume() noexcept {} // NOLINT

inline original::coroutine::task<void>
original::coroutine::task<void>::promise_type::get_return_object()
{
    return task{handle::from_promise(*this)};
}

inline auto original::coroutine::task<void>::promise_type::initial_suspend() // NOLINT
{
    return std::suspend_always{};
}

inline original::coroutine::task<void>::finalAwaitable
original::coroutine::task<void>::promise_type::final_suspend() noexcept // NOLINT
{
    return finalAwaitable{};
}

inline void original::coroutine::task<void>::promise_type::return_void() {} // NOLINT

inline void original::coroutine::task<void>::promise_type::unhandled_exception()
{
    this->e_ = std::current_exception();
}

inline void original::coroutine::task<void>::promise_type::rethrow_if_exception() const
{
    if (this->e_)
        std::rethrow_exception(this->e_);
}

inline original::coroutine::task<void>::task(const handle h) : handle_(h) {}

inline bool original::coroutine::task<void>::start() const noexcept {
    if (this->empty())
        return false;

    auto& promise = this->handle_.promise();
    switch (promise.state_) {
        case state::STANDBY:
            if (this->hasExecutor()){
                promise.state_ = state::RUNNING;
                promise.executor_->schedule(this->handle_);
                return true;
            }
            break;
        case state::RUNNING:
        case state::FINISHED:
        default:
            break;
    }
    return false;
}

inline bool original::coroutine::task<void>::hasExecutor() const noexcept
{
    if (this->empty())
        return false;

    return this->handle_.promise().executor_;
}

inline original::coroutine::task<void>&
original::coroutine::task<void>::via(executor& executor) noexcept {
    if (this->empty())
        return *this;

    auto& promise = this->handle_.promise();
    promise.executor_ = &executor;
    return *this;
}

inline original::coroutine::task<void>&
original::coroutine::task<void>::viaNext(executor& executor) noexcept
{
    if (this->empty())
        return *this;

    auto& promise = this->handle_.promise();
    promise.next_exec_ = &executor;
    return *this;
}

inline original::coroutine::task<void>::task(task&& other) noexcept
{
    this->handle_ = other.handle_;
    other.handle_ = nullptr;
}

inline original::coroutine::task<void>&
original::coroutine::task<void>::operator=(task&& other) noexcept
{
    if (this == &other)
        return *this;

    if (!this->empty())
        this->handle_.destroy();

    this->handle_ = other.handle_;
    other.handle_ = nullptr;
    return *this;
}

inline bool original::coroutine::task<void>::started() const noexcept {
    if (this->empty())
        return false;

    const auto& promise = this->handle_.promise();
    return promise.state_ != state::STANDBY;
}

inline bool original::coroutine::task<void>::finished() const noexcept
{
    if (this->empty())
        return false;

    const auto& promise = this->handle_.promise();
    return promise.state_ == state::FINISHED && this->handle_.done();
}

inline bool original::coroutine::task<void>::empty() const noexcept {
    return !this->handle_;
}

inline original::coroutine::task<void>::operator bool() const noexcept
{
    return this->handle_ != nullptr;
}

inline original::coroutine::task<void>::awaitable
original::coroutine::task<void>::operator co_await() const noexcept
{
    return awaitable{this->handle_};
}

inline void original::coroutine::task<void>::result() const
{
    if (this->empty())
        throw valueError("Can not get result from an empty task");

    const auto& promise = handle_.promise();
    switch (promise.state_) {
        case state::STANDBY:
        default:
            throw sysError("Task not started");

        case state::RUNNING:
            throw sysError("Task not finished");

        case state::FINISHED:
            break;
    }
    promise.rethrow_if_exception();
}

template <typename U>
original::coroutine::task<U>
original::coroutine::task<void>::operator|(task<U> rhs)
{
    if (this->empty() || rhs.empty())
        throw valueError("Can not combine empty tasks");

    auto sequence = []<typename LHS, typename RHS>(task<LHS> l, task<RHS> r) mutable -> task<U> {
        co_await l;
        co_return co_await r;
    };
    return sequence(std::move(*this), std::move(rhs));
}

template <typename U>
original::coroutine::task<U>
original::coroutine::task<void>::operator>>(task<U> rhs)
{
    if (this->empty() || rhs.empty())
        throw valueError("Can not combine empty tasks");

    return std::move(*this) | std::move(rhs);
}

template <typename Callback>
auto original::coroutine::task<void>::operator|(Callback&& c)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    const auto exec = this->handle_.promise().executor_;
    return std::move(*this) | std::move(makeTask(*exec, std::forward<Callback>(c)));
}

template <typename Callback>
auto original::coroutine::task<void>::operator>>(Callback&& c)
{
    if (this->empty())
        throw valueError("Can not combine empty tasks");

    return std::move(*this) >> std::forward<Callback>(c);
}

inline original::coroutine::task<void>::~task()
{
    if (!this->empty())
        this->handle_.destroy();
}

template<typename Callback, typename... Args>
auto original::coroutine::makeTask(executor& executor, Callback&& c, Args&&... args)
     -> task<std::invoke_result_t<Callback, Args...>> {
    using Return = std::invoke_result_t<Callback, Args...>;
    using Func  = std::decay_t<Callback>;
    using Tuple = std::tuple<std::decay_t<Args>...>;

    Func func_copy{std::forward<Callback>(c)};
    Tuple args_copy{std::forward<Args>(args)...};
    auto run_impl = [](original::executor& exec, Func f, Tuple tup) -> task<Return>
    {
        co_await exec;
        co_return std::apply(std::move(f), std::move(tup));
    };
    auto t = run_impl(executor, std::move(func_copy), std::move(args_copy));
    t.via(executor);
    return t;
}

#endif //ORIGINAL_COROUTINES_H
