# .github/workflows/basic-tests.yml

name: Test Branch CI - Basic Tests

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Test (${{ matrix.build_type }} - ${{ matrix.sanitizer }})

    strategy:
      matrix:
        build_type: [Debug]
        sanitizer: [none, asan, ubsan]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ ninja-build libgtest-dev

      - name: Configure CMake
        run: |
          EXTRA_ARGS=()
          
          case "${{ matrix.sanitizer }}" in
            "asan")
              EXTRA_ARGS+=(-DCMAKE_CXX_FLAGS=-fsanitize=address)
              EXTRA_ARGS+=(-DCMAKE_EXE_LINKER_FLAGS=-fsanitize=address)
              ;;
            "ubsan") 
              EXTRA_ARGS+=(-DCMAKE_CXX_FLAGS=-fsanitize=undefined -fno-sanitize-recover)
              EXTRA_ARGS+=(-DCMAKE_EXE_LINKER_FLAGS=-fsanitize=undefined)
              ;;
          esac
          
          echo "Configuring with extra args: ${EXTRA_ARGS[@]}"
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -G Ninja "${EXTRA_ARGS[@]}"

      - name: Build
        run: cmake --build build

      - name: List test executables
        run: find build -name "*test*" -type f -executable | grep -v ".a$" | sort

      - name: Show available tests
        run: cd build && ctest -N

      - name: Run tests
        run: cd build && ctest --verbose --output-on-failure