# .github/workflows/deploy-docs-stable.yml

name: Deploy Documentation - Stable

on:
  push:
    branches: [ master, test ] # Temporary add test branch to deploy list

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz plantuml

      - name: Build documentation
        run: |
          # Create the necessary directory structure
          mkdir -p ../original_docs
          
          # Run doxygen
          doxygen Doxyfile
          
          # Check whether the document was generated successfully
          if [ ! -d "../original_docs/docs/html" ]; then
            echo "Error: Documentation was not generated in expected location"
            ls -la ../original_docs/docs/ || echo "Docs directory not found"
            exit 1
          fi
          
          # Create version information file
          echo '<!DOCTYPE html>' > ../original_docs/docs/html/version.html
          echo '<html>' >> ../original_docs/docs/html/version.html
          echo '<head>' >> ../original_docs/docs/html/version.html
          echo '    <title>Version Info</title>' >> ../original_docs/docs/html/version.html
          echo '</head>' >> ../original_docs/docs/html/version.html
          echo '<body>' >> ../original_docs/docs/html/version.html
          echo '    <h1>Documentation Version</h1>' >> ../original_docs/docs/html/version.html
          echo '    <p>Version: stable</p>' >> ../original_docs/docs/html/version.html
          echo '    <p>Branch: master</p>' >> index.html
          echo "    <p>Build Date: $(date -u)</p>" >> ../original_docs/docs/html/version.html
          echo "    <p>Commit: ${{ github.sha }}</p>" >> ../original_docs/docs/html/version.html
          echo '</body>' >> ../original_docs/docs/html/version.html
          echo '</html>' >> ../original_docs/docs/html/version.html

      - name: Deploy to original_docs repository
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Clone document repository
          git clone -b master https://${{ secrets.GH_PAT }}@github.com/FrozenLemonTee/original_docs.git deploy-repo
          
          cd deploy-repo
          
          # Only update stable directory
          rm -rf stable
          mkdir -p stable
          cp -r ../../original_docs/docs/html/* stable/
          
          # Create index.html redirection
          echo '<!DOCTYPE html>' > index.html
          echo '<html>' >> index.html
          echo '<head>' >> index.html
          echo '    <meta http-equiv="refresh" content="0; url=stable/index.html">' >> index.html
          echo '</head>' >> index.html
          echo '<body>' >> index.html
          echo '    <p>Redirecting to <a href="stable/index.html">stable documentation</a>...</p>' >> index.html
          echo '    <p>Available versions:</p>' >> index.html
          echo '    <ul>' >> index.html
          echo '        <li><a href="stable/index.html">Stable (master branch)</a></li>' >> index.html
          echo '        <li><a href="latest/index.html">Latest (test branch)</a></li>' >> index.html
          echo '        <li><a href="versions/">Tag versions</a></li>' >> index.html
          echo '    </ul>' >> index.html
          echo '</body>' >> index.html
          echo '</html>' >> index.html
          
          # Submit and push
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to deploy"
          else
            git commit -m "Deploy ${{ steps.version.outputs.docs-version }} documentation from ${{ github.sha }}"
            git push origin master
            echo "✅ Stable documentation deployed successfully"
          fi